function alpha_air = alpha_air_fun(in1,in2,b_C,in4)
%ALPHA_AIR_FUN
%    ALPHA_AIR = ALPHA_AIR_FUN(IN1,IN2,b_C,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Oct-2021 11:02:41

A_p0 = in2(1,:);
A_p1 = in2(2,:);
A_p2 = in2(3,:);
A_p3 = in2(4,:);
A_p4 = in2(5,:);
A_p5 = in2(6,:);
d_Ca = in4(1,:);
d_Cb = in4(2,:);
l_p0 = in1(1,:);
l_p1 = in1(2,:);
l_p2 = in1(3,:);
l_p3 = in1(4,:);
l_p4 = in1(5,:);
l_p5 = in1(6,:);
mt1 = [A_p0.*l_p0.*1.0e+5-b_C.*(d_Ca.*(1.1e+1./1.0e+2)-d_Cb.*(1.1e+1./1.0e+2)).*1.0e+5,A_p1.*l_p1.*1.0e+5-b_C.*(d_Ca.*(1.1e+1./1.0e+2)-d_Cb.*(1.1e+1./1.0e+2)).*1.0e+5,A_p2.*l_p2.*1.0e+5-b_C.*(d_Ca.*(1.1e+1./1.0e+2)-d_Cb.*(1.1e+1./1.0e+2)).*1.0e+5,A_p3.*l_p3.*1.0e+5-b_C.*(d_Ca.*(1.1e+1./1.0e+2)-d_Cb.*(1.1e+1./1.0e+2)).*1.0e+5,A_p4.*l_p4.*1.0e+5-b_C.*(d_Ca.*(1.1e+1./1.0e+2)-d_Cb.*(1.1e+1./1.0e+2)).*1.0e+5];
mt2 = [A_p5.*l_p5.*1.0e+5-b_C.*(d_Ca.*(1.1e+1./1.0e+2)-d_Cb.*(1.1e+1./1.0e+2)).*1.0e+5];
alpha_air = reshape([mt1,mt2],6,1);
