function alpha_air = alpha_air_fun(in1,in2,in3,b_C,in5)
%ALPHA_AIR_FUN
%    ALPHA_AIR = ALPHA_AIR_FUN(IN1,IN2,IN3,B_C,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-May-2021 11:57:49

A_p0 = in3(1,:);
A_p1 = in3(2,:);
A_p2 = in3(3,:);
A_p3 = in3(4,:);
A_p4 = in3(5,:);
A_p5 = in3(6,:);
d_Ca = in5(1,:);
d_Cb = in5(2,:);
l0 = in1(1,:);
l1 = in1(2,:);
l2 = in1(3,:);
l_p0 = in2(1,:);
l_p1 = in2(2,:);
l_p2 = in2(3,:);
l_p3 = in2(4,:);
l_p4 = in2(5,:);
l_p5 = in2(6,:);
alpha_air = [A_p0.*l_p0.*1.0e+5-b_C.*l0.*(d_Ca-d_Cb).*1.0e+5;A_p1.*l_p1.*1.0e+5-b_C.*l0.*(d_Ca-d_Cb).*1.0e+5;A_p2.*l_p2.*1.0e+5-b_C.*l1.*(d_Ca-d_Cb).*1.0e+5;A_p3.*l_p3.*1.0e+5-b_C.*l1.*(d_Ca-d_Cb).*1.0e+5;A_p4.*l_p4.*1.0e+5-b_C.*l2.*(d_Ca-d_Cb).*1.0e+5;A_p5.*l_p5.*1.0e+5-b_C.*l2.*(d_Ca-d_Cb).*1.0e+5];
