function B0_ds = B0_ds_fun(s,in2,alpha,in4,in5)
%B0_DS_FUN
%    B0_DS = B0_DS_FUN(S,IN2,ALPHA,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-May-2021 11:57:38

l0 = in4(1,:);
q0 = in2(1,:);
rho0 = in5(1,:);
B0_ds = reshape([rho0.*(l0.*1.0./q0.^2.*(cos(alpha+(q0.*s)./l0)-cos(alpha))+(s.*sin(alpha+(q0.*s)./l0))./q0).^2+rho0.*(l0.*1.0./q0.^2.*(sin(alpha+(q0.*s)./l0)-sin(alpha))-(s.*cos(alpha+(q0.*s)./l0))./q0).^2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
