function B1_ds = B1_ds_fun(s,in2,alpha,in4,in5)
%B1_DS_FUN
%    B1_DS = B1_DS_FUN(S,IN2,ALPHA,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-May-2021 11:57:38

l0 = in4(1,:);
l1 = in4(2,:);
q0 = in2(1,:);
q1 = in2(2,:);
rho1 = in5(2,:);
B1_ds = reshape([rho1.*(-(l0.*cos(alpha+q0))./q0+(l1.*(cos(alpha+q0)-cos(alpha+q0+(q1.*s)./l1)))./q1+l0.*1.0./q0.^2.*(sin(alpha+q0)-sin(alpha))).^2+rho1.*((l0.*sin(alpha+q0))./q0-(l1.*(sin(alpha+q0)-sin(alpha+q0+(q1.*s)./l1)))./q1+l0.*1.0./q0.^2.*(cos(alpha+q0)-cos(alpha))).^2,-rho1.*((s.*cos(alpha+q0+(q1.*s)./l1))./q1+l1.*1.0./q1.^2.*(sin(alpha+q0)-sin(alpha+q0+(q1.*s)./l1))).*(-(l0.*cos(alpha+q0))./q0+(l1.*(cos(alpha+q0)-cos(alpha+q0+(q1.*s)./l1)))./q1+l0.*1.0./q0.^2.*(sin(alpha+q0)-sin(alpha)))+rho1.*((s.*sin(alpha+q0+(q1.*s)./l1))./q1-l1.*1.0./q1.^2.*(cos(alpha+q0)-cos(alpha+q0+(q1.*s)./l1))).*((l0.*sin(alpha+q0))./q0-(l1.*(sin(alpha+q0)-sin(alpha+q0+(q1.*s)./l1)))./q1+l0.*1.0./q0.^2.*(cos(alpha+q0)-cos(alpha))),0.0,-rho1.*((s.*cos(alpha+q0+(q1.*s)./l1))./q1+l1.*1.0./q1.^2.*(sin(alpha+q0)-sin(alpha+q0+(q1.*s)./l1))).*(-(l0.*cos(alpha+q0))./q0+(l1.*(cos(alpha+q0)-cos(alpha+q0+(q1.*s)./l1)))./q1+l0.*1.0./q0.^2.*(sin(alpha+q0)-sin(alpha)))+rho1.*((s.*sin(alpha+q0+(q1.*s)./l1))./q1-l1.*1.0./q1.^2.*(cos(alpha+q0)-cos(alpha+q0+(q1.*s)./l1))).*((l0.*sin(alpha+q0))./q0-(l1.*(sin(alpha+q0)-sin(alpha+q0+(q1.*s)./l1)))./q1+l0.*1.0./q0.^2.*(cos(alpha+q0)-cos(alpha))),rho1.*((s.*sin(alpha+q0+(q1.*s)./l1))./q1-l1.*1.0./q1.^2.*(cos(alpha+q0)-cos(alpha+q0+(q1.*s)./l1))).^2+rho1.*((s.*cos(alpha+q0+(q1.*s)./l1))./q1+l1.*1.0./q1.^2.*(sin(alpha+q0)-sin(alpha+q0+(q1.*s)./l1))).^2,0.0,0.0,0.0,0.0],[3,3]);
