function G = G_fun(in1,alpha,in3)
%G_FUN
%    G = G_FUN(IN1,ALPHA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    24-May-2021 16:04:34

gx = in3(1,:);
gy = in3(2,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
G = [gx.*1.0./q1.^2.*(sin(alpha+q0+q1)-sin(alpha+q0)).*1.1979e-2+(gy.*(sin(alpha+q0+q1)-sin(alpha+q0)).*1.1979e-2)./q1+(gx.*cos(alpha+q0).*2.3958e-2)./q0-(gx.*cos(alpha+q0).*1.1979e-2)./q1-gy.*1.0./q0.^2.*cos(alpha+q0).*1.1979e-2+gx.*1.0./q0.^2.*sin(alpha+q0).*1.1979e-2+(gy.*sin(alpha+q0).*2.3958e-2)./q0-(gy.*sin(alpha+q0).*1.1979e-2)./q1-gy.*1.0./q0.^2.*cos(alpha).*1.1979e-2+gx.*1.0./q0.^2.*sin(alpha).*1.1979e-2-(gx.*cos(alpha+q0+q1).*1.1979e-2)./q2-(gy.*sin(alpha+q0+q1).*1.1979e-2)./q2+gx.*1.0./q0.^3.*(cos(alpha+q0)-cos(alpha)).*2.3958e-2+gy.*1.0./q0.^2.*(cos(alpha+q0)-cos(alpha)).*2.3958e-2-gx.*1.0./q0.^2.*(sin(alpha+q0)-sin(alpha)).*2.3958e-2+gy.*1.0./q0.^3.*(sin(alpha+q0)-sin(alpha)).*2.3958e-2+gy.*1.0./q2.^2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+q2)).*1.1979e-2+(gx.*(cos(alpha+q0+q1)-cos(alpha+q0)).*1.1979e-2)./q1-gy.*1.0./q1.^2.*(cos(alpha+q0+q1)-cos(alpha+q0)).*1.1979e-2-gx.*1.0./q2.^2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+q2)).*1.1979e-2;1.0./q1.^3.*1.0./q2.^2.*(gy.*q1.^3.*cos(alpha+q0+q1+q2).*1.1979e+4-gx.*q1.^3.*sin(alpha+q0+q1+q2).*1.1979e+4+gx.*q2.^2.*cos(alpha+q0).*2.3958e+4+gy.*q2.^2.*sin(alpha+q0).*2.3958e+4-gx.*q2.^2.*cos(alpha+q0+q1).*2.3958e+4-gy.*q1.^3.*cos(alpha+q0+q1).*1.1979e+4+gx.*q1.^3.*sin(alpha+q0+q1).*1.1979e+4-gy.*q2.^2.*sin(alpha+q0+q1).*2.3958e+4+gx.*q1.^3.*q2.*cos(alpha+q0+q1).*1.1979e+4+gy.*q1.^3.*q2.*sin(alpha+q0+q1).*1.1979e+4-gx.*q1.^2.*q2.^2.*cos(alpha+q0+q1).*1.1979e+4-gy.*q1.^2.*q2.^2.*sin(alpha+q0+q1).*1.1979e+4+gy.*q1.*q2.^2.*cos(alpha+q0).*2.3958e+4-gx.*q1.*q2.^2.*sin(alpha+q0).*2.3958e+4).*(-1.0e-6);gy.*1.0./q2.^2.*cos(alpha+q0+q1+q2).*(-1.1979e-2)+gx.*1.0./q2.^2.*sin(alpha+q0+q1+q2).*1.1979e-2-gy.*1.0./q2.^2.*cos(alpha+q0+q1).*1.1979e-2+gx.*1.0./q2.^2.*sin(alpha+q0+q1).*1.1979e-2-gx.*1.0./q2.^3.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+q2)).*2.3958e-2-gy.*1.0./q2.^3.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+q2)).*2.3958e-2];
