function G = G_fun(in1,alpha,in3)
%G_FUN
%    G = G_FUN(IN1,ALPHA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    18-May-2021 12:46:29

gx = in3(1,:);
gy = in3(2,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
G = [-1.0./q0.^3.*1.0./q1.^2.*1.0./q2.^2.*(gx.*q0.^3.*q2.^2.*sin(alpha+q0)-gy.*q1.^2.*q2.^2.*sin(alpha+q0).*2.0+gx.*q1.^2.*q2.^2.*cos(alpha).*2.0+gy.*q1.^2.*q2.^2.*sin(alpha).*2.0-gy.*q0.^3.*q1.^2.*cos(alpha+q0+q1)+gy.*q0.^3.*q2.^2.*cos(alpha+q0+q1)+gx.*q0.^3.*q1.^2.*sin(alpha+q0+q1)-gx.*q0.^3.*q2.^2.*sin(alpha+q0+q1)+gy.*q0.^3.*q1.^2.*cos(alpha+q0+q1+q2)-gx.*q0.^3.*q1.^2.*sin(alpha+q0+q1+q2)-gx.*q1.^2.*q2.^2.*cos(alpha+q0).*2.0-gy.*q0.^3.*q2.^2.*cos(alpha+q0)+gx.*q0.^3.*q1.*q2.^2.*cos(alpha+q0).*2.0-gy.*q0.*q1.^2.*q2.^2.*cos(alpha+q0)+gx.*q0.*q1.^2.*q2.^2.*sin(alpha+q0)+gy.*q0.^3.*q1.*q2.^2.*sin(alpha+q0).*2.0+gy.*q0.*q1.^2.*q2.^2.*cos(alpha).*3.0-gx.*q0.*q1.^2.*q2.^2.*sin(alpha).*3.0-gx.*q0.^2.*q1.^2.*q2.^2.*cos(alpha+q0).*2.0-gy.*q0.^2.*q1.^2.*q2.^2.*sin(alpha+q0).*2.0-gx.*q0.^3.*q1.*q2.^2.*cos(alpha+q0+q1)+gx.*q0.^3.*q1.^2.*q2.*cos(alpha+q0+q1)-gy.*q0.^3.*q1.*q2.^2.*sin(alpha+q0+q1)+gy.*q0.^3.*q1.^2.*q2.*sin(alpha+q0+q1));-1.0./q1.^3.*1.0./q2.^2.*(gy.*q1.^3.*cos(alpha+q0+q1+q2)-gx.*q1.^3.*sin(alpha+q0+q1+q2)+gx.*q2.^2.*cos(alpha+q0).*2.0+gy.*q2.^2.*sin(alpha+q0).*2.0-gx.*q2.^2.*cos(alpha+q0+q1).*2.0-gy.*q1.^3.*cos(alpha+q0+q1)+gx.*q1.^3.*sin(alpha+q0+q1)-gy.*q2.^2.*sin(alpha+q0+q1).*2.0+gx.*q1.^3.*q2.*cos(alpha+q0+q1)+gy.*q1.^3.*q2.*sin(alpha+q0+q1)-gx.*q1.^2.*q2.^2.*cos(alpha+q0+q1)-gy.*q1.^2.*q2.^2.*sin(alpha+q0+q1)+gy.*q1.*q2.^2.*cos(alpha+q0).*2.0-gx.*q1.*q2.^2.*sin(alpha+q0).*2.0);-gy.*1.0./q2.^2.*cos(alpha+q0+q1+q2)+gx.*1.0./q2.^2.*sin(alpha+q0+q1+q2)-gy.*1.0./q2.^2.*cos(alpha+q0+q1)+gx.*1.0./q2.^2.*sin(alpha+q0+q1)-gx.*1.0./q2.^3.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+q2)).*2.0-gy.*1.0./q2.^3.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+q2)).*2.0];
