function theta2 = q2theta2_fun(s,in2,alpha,in4)
%Q2THETA2_FUN
%    THETA2 = Q2THETA2_FUN(S,IN2,ALPHA,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-May-2021 11:57:38

l2 = in4(3,:);
q0 = in2(1,:);
q1 = in2(2,:);
q2 = in2(3,:);
theta2 = alpha+q0+q1+(q2.*s)./l2;
