function theta1 = q2theta1_fun(s,in2,alpha)
%Q2THETA1_FUN
%    THETA1 = Q2THETA1_FUN(S,IN2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    24-May-2021 16:04:28

q0 = in2(1,:);
q1 = in2(2,:);
theta1 = alpha+q0+q1.*s.*(1.0e+2./1.1e+1);
