function theta0 = q2theta0_fun(s,in2,alpha,in4)
%Q2THETA0_FUN
%    THETA0 = Q2THETA0_FUN(S,IN2,ALPHA,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-May-2021 11:57:37

l0 = in4(1,:);
q0 = in2(1,:);
theta0 = alpha+(q0.*s)./l0;
