function x0 = q2x0_fun(s,in2,alpha)
%Q2X0_FUN
%    X0 = Q2X0_FUN(S,IN2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Oct-2021 11:02:31

q0 = in2(1,:);
x0 = [((sin(alpha+q0.*s.*(1.0e+2./1.1e+1))-sin(alpha)).*(1.1e+1./1.0e+2))./q0;((cos(alpha+q0.*s.*(1.0e+2./1.1e+1))-cos(alpha)).*(-1.1e+1./1.0e+2))./q0];
