function x1 = q2x1_fun(s,in2,alpha,in4)
%Q2X1_FUN
%    X1 = Q2X1_FUN(S,IN2,ALPHA,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-May-2021 11:57:38

l0 = in4(1,:);
l1 = in4(2,:);
q0 = in2(1,:);
q1 = in2(2,:);
x1 = [-(l1.*(sin(alpha+q0)-sin(alpha+q0+(q1.*s)./l1)))./q1+(l0.*(sin(alpha+q0)-sin(alpha)))./q0;(l1.*(cos(alpha+q0)-cos(alpha+q0+(q1.*s)./l1)))./q1-(l0.*(cos(alpha+q0)-cos(alpha)))./q0];
