function x1 = q2x1_fun(s,in2,alpha)
%Q2X1_FUN
%    X1 = Q2X1_FUN(S,IN2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    18-May-2021 12:46:19

q0 = in2(1,:);
q1 = in2(2,:);
x1 = [(sin(alpha+q0)-sin(alpha))./q0-(sin(alpha+q0)-sin(alpha+q0+q1.*s))./q1;-(cos(alpha+q0)-cos(alpha))./q0+(cos(alpha+q0)-cos(alpha+q0+q1.*s))./q1];
