function x2 = q2x2_fun(s,in2,alpha,in4)
%Q2X2_FUN
%    X2 = Q2X2_FUN(S,IN2,ALPHA,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-May-2021 11:57:38

l0 = in4(1,:);
l1 = in4(2,:);
l2 = in4(3,:);
q0 = in2(1,:);
q1 = in2(2,:);
q2 = in2(3,:);
x2 = [(l1.*(sin(alpha+q0+q1)-sin(alpha+q0)))./q1-(l2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2)))./q2+(l0.*(sin(alpha+q0)-sin(alpha)))./q0;(l2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2)))./q2-(l0.*(cos(alpha+q0)-cos(alpha)))./q0-(l1.*(cos(alpha+q0+q1)-cos(alpha+q0)))./q1];
