function V_C = V_C_fun(in1,b_C,in3)
%V_C_FUN
%    V_C = V_C_FUN(IN1,B_C,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    07-Sep-2021 10:55:58

d_Ca = in3(1,:);
d_Cb = in3(2,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
mt1 = [b_C.*(d_Ca.*(-1.1e+1./1.0e+2)+d_Cb.*(1.1e+1./1.0e+2)+(q0.*(d_Ca.^2-d_Cb.^2))./2.0),-b_C.*(d_Ca.*(1.1e+1./1.0e+2)-d_Cb.*(1.1e+1./1.0e+2)+(q0.*(d_Ca.^2-d_Cb.^2))./2.0),b_C.*(d_Ca.*(-1.1e+1./1.0e+2)+d_Cb.*(1.1e+1./1.0e+2)+(q1.*(d_Ca.^2-d_Cb.^2))./2.0),-b_C.*(d_Ca.*(1.1e+1./1.0e+2)-d_Cb.*(1.1e+1./1.0e+2)+(q1.*(d_Ca.^2-d_Cb.^2))./2.0),b_C.*(d_Ca.*(-1.1e+1./1.0e+2)+d_Cb.*(1.1e+1./1.0e+2)+(q2.*(d_Ca.^2-d_Cb.^2))./2.0)];
mt2 = [-b_C.*(d_Ca.*(1.1e+1./1.0e+2)-d_Cb.*(1.1e+1./1.0e+2)+(q2.*(d_Ca.^2-d_Cb.^2))./2.0)];
V_C = reshape([mt1,mt2],6,1);
