function V = V_fun(in1,in2,in3,b_C,in5)
%V_fun
%    V = V_fun(IN1,IN2,IN3,b_C,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Oct-2021 11:02:41

A_p0 = in3(1,:);
A_p1 = in3(2,:);
A_p2 = in3(3,:);
A_p3 = in3(4,:);
A_p4 = in3(5,:);
A_p5 = in3(6,:);
d_Ca = in5(1,:);
d_Cb = in5(2,:);
mu_p0 = in2(1,:);
mu_p1 = in2(2,:);
mu_p2 = in2(3,:);
mu_p3 = in2(4,:);
mu_p4 = in2(5,:);
mu_p5 = in2(6,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
mt1 = [A_p0.*mu_p0+b_C.*(d_Ca.*(-1.1e+1./1.0e+2)+d_Cb.*(1.1e+1./1.0e+2)+(q0.*(d_Ca.^2-d_Cb.^2))./2.0),A_p1.*mu_p1-b_C.*(d_Ca.*(1.1e+1./1.0e+2)-d_Cb.*(1.1e+1./1.0e+2)+(q0.*(d_Ca.^2-d_Cb.^2))./2.0),A_p2.*mu_p2+b_C.*(d_Ca.*(-1.1e+1./1.0e+2)+d_Cb.*(1.1e+1./1.0e+2)+(q1.*(d_Ca.^2-d_Cb.^2))./2.0),A_p3.*mu_p3-b_C.*(d_Ca.*(1.1e+1./1.0e+2)-d_Cb.*(1.1e+1./1.0e+2)+(q1.*(d_Ca.^2-d_Cb.^2))./2.0),A_p4.*mu_p4+b_C.*(d_Ca.*(-1.1e+1./1.0e+2)+d_Cb.*(1.1e+1./1.0e+2)+(q2.*(d_Ca.^2-d_Cb.^2))./2.0)];
mt2 = [A_p5.*mu_p5-b_C.*(d_Ca.*(1.1e+1./1.0e+2)-d_Cb.*(1.1e+1./1.0e+2)+(q2.*(d_Ca.^2-d_Cb.^2))./2.0)];
V = reshape([mt1,mt2],6,1);
