function V_p = V_p_fun(in1,in2)
%V_p_fun
%    V_p = V_p_fun(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Oct-2021 11:02:41

A_p0 = in2(1,:);
A_p1 = in2(2,:);
A_p2 = in2(3,:);
A_p3 = in2(4,:);
A_p4 = in2(5,:);
A_p5 = in2(6,:);
mu_p0 = in1(1,:);
mu_p1 = in1(2,:);
mu_p2 = in1(3,:);
mu_p3 = in1(4,:);
mu_p4 = in1(5,:);
mu_p5 = in1(6,:);
V_p = [A_p0.*mu_p0;A_p1.*mu_p1;A_p2.*mu_p2;A_p3.*mu_p3;A_p4.*mu_p4;A_p5.*mu_p5];
