function B0_ds = B0_ds_fun(s,in2,alpha,in4,in5)
%B0_DS_FUN
%    B0_DS = B0_DS_FUN(S,IN2,ALPHA,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Apr-2021 12:10:47

l0 = in4(1,:);
q0 = in2(1,:);
rho0 = in5(1,:);
et1 = 1.0./q0.^2.*rho0.*((q0.*sin((1.0./abs(l0).^2.*(l0.*abs(q0).^2.*abs(s).^2+q0.*s.*conj(alpha).*abs(l0).^2))./(q0.*s)).*1.0./abs(q0).^2.*abs(s).^2)./s-(q0.^2.*abs(l0).^2.*1.0./abs(q0).^4.*(cos(conj(alpha))-cos((1.0./abs(l0).^2.*(l0.*abs(q0).^2.*abs(s).^2+q0.*s.*conj(alpha).*abs(l0).^2))./(q0.*s))))./l0).*(l0.*cos((alpha.*l0+q0.*s)./l0)-l0.*cos(alpha)+q0.*s.*sin((alpha.*l0+q0.*s)./l0));
et2 = 1.0./q0.^2.*rho0.*((q0.*cos((1.0./abs(l0).^2.*(l0.*abs(q0).^2.*abs(s).^2+q0.*s.*conj(alpha).*abs(l0).^2))./(q0.*s)).*1.0./abs(q0).^2.*abs(s).^2)./s+(q0.^2.*abs(l0).^2.*1.0./abs(q0).^4.*(sin(conj(alpha))-sin((1.0./abs(l0).^2.*(l0.*abs(q0).^2.*abs(s).^2+q0.*s.*conj(alpha).*abs(l0).^2))./(q0.*s))))./l0).*(-l0.*sin((alpha.*l0+q0.*s)./l0)+l0.*sin(alpha)+q0.*s.*cos((alpha.*l0+q0.*s)./l0));
B0_ds = reshape([et1+et2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
