function B1_ds = B1_ds_fun(s,in2,alpha,in4,in5)
%B1_DS_FUN
%    B1_DS = B1_DS_FUN(S,IN2,ALPHA,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Apr-2021 12:10:47

l0 = in4(1,:);
l1 = in4(2,:);
q0 = in2(1,:);
q1 = in2(2,:);
rho1 = in5(2,:);
et1 = rho1.*(q1.*sin(conj(alpha)+conj(q0)+(l1.*1.0./abs(l1).^2.*abs(q1).^2.*conj(s))./q1).*1.0./abs(q1).^2.*conj(s)+(q1.^2.*abs(l1).^2.*1.0./abs(q1).^4.*(cos(conj(alpha)+conj(q0)+(l1.*1.0./abs(l1).^2.*abs(q1).^2.*conj(s))./q1)-cos(conj(alpha)+conj(q0))))./l1).*((l0.*sin(alpha+q0))./q0-(l1.*(sin(alpha+q0)-sin((alpha.*l1+l1.*q0+q1.*s)./l1)))./q1+l0.*1.0./q0.^2.*(cos(alpha+q0)-cos(alpha)));
et2 = -rho1.*(q1.*cos(conj(alpha)+conj(q0)+(l1.*1.0./abs(l1).^2.*abs(q1).^2.*conj(s))./q1).*1.0./abs(q1).^2.*conj(s)-(q1.^2.*abs(l1).^2.*1.0./abs(q1).^4.*(sin(conj(alpha)+conj(q0)+(l1.*1.0./abs(l1).^2.*abs(q1).^2.*conj(s))./q1)-sin(conj(alpha)+conj(q0))))./l1).*(-(l0.*cos(alpha+q0))./q0+(l1.*(cos(alpha+q0)-cos((alpha.*l1+l1.*q0+q1.*s)./l1)))./q1+l0.*1.0./q0.^2.*(sin(alpha+q0)-sin(alpha)));
et3 = rho1.*((q1.*abs(l1).^2.*1.0./abs(q1).^2.*(sin((1.0./abs(l1).^2.*(q1.*abs(l1).^2.*abs(q0).^2+q0.*q1.*conj(alpha).*abs(l1).^2+l1.*q0.*abs(q1).^2.*conj(s)))./(q0.*q1))-sin((abs(q0).^2+q0.*conj(alpha))./q0)))./l1+(q0.*sin((abs(q0).^2+q0.*conj(alpha))./q0).*abs(l0).^2.*1.0./abs(q0).^2)./l0-(q0.^2.*abs(l0).^2.*1.0./abs(q0).^4.*(cos(conj(alpha))-cos((abs(q0).^2+q0.*conj(alpha))./q0)))./l0);
et4 = (l0.*sin(alpha+q0))./q0-(l1.*(sin(alpha+q0)-sin((alpha.*l1+l1.*q0+q1.*s)./l1)))./q1+l0.*1.0./q0.^2.*(cos(alpha+q0)-cos(alpha));
et5 = rho1.*((q1.*abs(l1).^2.*1.0./abs(q1).^2.*(cos((1.0./abs(l1).^2.*(q1.*abs(l1).^2.*abs(q0).^2+q0.*q1.*conj(alpha).*abs(l1).^2+l1.*q0.*abs(q1).^2.*conj(s)))./(q0.*q1))-cos((abs(q0).^2+q0.*conj(alpha))./q0)))./l1+(q0.^2.*abs(l0).^2.*1.0./abs(q0).^4.*(sin(conj(alpha))-sin((abs(q0).^2+q0.*conj(alpha))./q0)))./l0+(q0.*cos((abs(q0).^2+q0.*conj(alpha))./q0).*abs(l0).^2.*1.0./abs(q0).^2)./l0);
et6 = -(-(l0.*cos(alpha+q0))./q0+(l1.*(cos(alpha+q0)-cos((alpha.*l1+l1.*q0+q1.*s)./l1)))./q1+l0.*1.0./q0.^2.*(sin(alpha+q0)-sin(alpha)));
et7 = 1.0./q1.^2.*rho1.*((q1.*sin(conj(alpha)+conj(q0)+(l1.*1.0./abs(l1).^2.*abs(q1).^2.*abs(s).^2)./(q1.*s)).*1.0./abs(q1).^2.*abs(s).^2)./s-(q1.^2.*abs(l1).^2.*1.0./abs(q1).^4.*(cos(conj(alpha)+conj(q0))-cos(conj(alpha)+conj(q0)+(l1.*1.0./abs(l1).^2.*abs(q1).^2.*abs(s).^2)./(q1.*s))))./l1).*(-l1.*cos(alpha+q0)+l1.*cos((alpha.*l1+l1.*q0+q1.*s)./l1)+q1.*s.*sin((alpha.*l1+l1.*q0+q1.*s)./l1));
et8 = 1.0./q1.^2.*rho1.*((q1.*cos(conj(alpha)+conj(q0)+(l1.*1.0./abs(l1).^2.*abs(q1).^2.*abs(s).^2)./(q1.*s)).*1.0./abs(q1).^2.*abs(s).^2)./s+(q1.^2.*abs(l1).^2.*1.0./abs(q1).^4.*(sin(conj(alpha)+conj(q0))-sin(conj(alpha)+conj(q0)+(l1.*1.0./abs(l1).^2.*abs(q1).^2.*abs(s).^2)./(q1.*s))))./l1).*(l1.*sin(alpha+q0)-l1.*sin((alpha.*l1+l1.*q0+q1.*s)./l1)+q1.*s.*cos((alpha.*l1+l1.*q0+q1.*s)./l1));
et9 = 1.0./q1.^2.*rho1.*(l1.*sin(alpha+q0)-l1.*sin((alpha.*l1+l1.*q0+q1.*s)./l1)+q1.*s.*cos((alpha.*l1+l1.*q0+q1.*s)./l1)).*((cos(conj(alpha)+conj(q0)).*conj(l0))./conj(q0)+conj(l0).*1.0./conj(q0).^2.*(sin(conj(alpha))-sin(conj(alpha)+conj(q0)))+(q1.*abs(l1).^2.*1.0./abs(q1).^2.*(cos(conj(alpha)+conj(q0)+(l1.*1.0./abs(l1).^2.*abs(q1).^2.*conj(s))./q1)-cos(conj(alpha)+conj(q0))))./l1);
et10 = 1.0./q1.^2.*rho1.*(-l1.*cos(alpha+q0)+l1.*cos((alpha.*l1+l1.*q0+q1.*s)./l1)+q1.*s.*sin((alpha.*l1+l1.*q0+q1.*s)./l1)).*(-conj(l0).*1.0./conj(q0).^2.*(cos(conj(alpha))-cos(conj(alpha)+conj(q0)))+(sin(conj(alpha)+conj(q0)).*conj(l0))./conj(q0)+(q1.*abs(l1).^2.*1.0./abs(q1).^2.*(sin(conj(alpha)+conj(q0)+(l1.*1.0./abs(l1).^2.*abs(q1).^2.*conj(s))./q1)-sin(conj(alpha)+conj(q0))))./l1);
B1_ds = reshape([et3.*et4+et5.*et6,et1+et2,0.0,et9+et10,et7+et8,0.0,0.0,0.0,0.0],[3,3]);
