function B2_ds = B2_ds_fun(s,in2,alpha,in4,in5)
%B2_DS_FUN
%    B2_DS = B2_DS_FUN(S,IN2,ALPHA,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Apr-2021 22:54:10

l0 = in4(1,:);
l1 = in4(2,:);
l2 = in4(3,:);
q0 = in2(1,:);
q1 = in2(2,:);
q2 = in2(3,:);
rho2 = in5(3,:);
et1 = rho2.*(l2.*1.0./q2.^2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2))+(s.*cos(alpha+q0+q1+(q2.*s)./l2))./q2).*((l0.*cos(alpha+q0))./q0-(l2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2)))./q2-l0.*1.0./q0.^2.*(sin(alpha+q0)-sin(alpha))+(l1.*(cos(alpha+q0+q1)-cos(alpha+q0)))./q1);
et2 = -rho2.*(l2.*1.0./q2.^2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2))-(s.*sin(alpha+q0+q1+(q2.*s)./l2))./q2).*((l1.*(sin(alpha+q0+q1)-sin(alpha+q0)))./q1+(l0.*sin(alpha+q0))./q0-(l2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2)))./q2+l0.*1.0./q0.^2.*(cos(alpha+q0)-cos(alpha)));
et3 = -rho2.*(l1.*1.0./q1.^2.*(sin(alpha+q0+q1)-sin(alpha+q0))+(l2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2)))./q2-(l1.*cos(alpha+q0+q1))./q1).*((l0.*cos(alpha+q0))./q0-(l2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2)))./q2-l0.*1.0./q0.^2.*(sin(alpha+q0)-sin(alpha))+(l1.*(cos(alpha+q0+q1)-cos(alpha+q0)))./q1);
et4 = rho2.*(-(l2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2)))./q2+(l1.*sin(alpha+q0+q1))./q1+l1.*1.0./q1.^2.*(cos(alpha+q0+q1)-cos(alpha+q0))).*((l1.*(sin(alpha+q0+q1)-sin(alpha+q0)))./q1+(l0.*sin(alpha+q0))./q0-(l2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2)))./q2+l0.*1.0./q0.^2.*(cos(alpha+q0)-cos(alpha)));
et5 = -rho2.*(l2.*1.0./q2.^2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2))+(s.*cos(alpha+q0+q1+(q2.*s)./l2))./q2).*(l1.*1.0./q1.^2.*(sin(alpha+q0+q1)-sin(alpha+q0))+(l2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2)))./q2-(l1.*cos(alpha+q0+q1))./q1);
et6 = -rho2.*(l2.*1.0./q2.^2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2))-(s.*sin(alpha+q0+q1+(q2.*s)./l2))./q2).*(-(l2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2)))./q2+(l1.*sin(alpha+q0+q1))./q1+l1.*1.0./q1.^2.*(cos(alpha+q0+q1)-cos(alpha+q0)));
et7 = -rho2.*(l1.*1.0./q1.^2.*(sin(alpha+q0+q1)-sin(alpha+q0))+(l2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2)))./q2-(l1.*cos(alpha+q0+q1))./q1).*((l0.*cos(alpha+q0))./q0-(l2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2)))./q2-l0.*1.0./q0.^2.*(sin(alpha+q0)-sin(alpha))+(l1.*(cos(alpha+q0+q1)-cos(alpha+q0)))./q1);
et8 = rho2.*(-(l2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2)))./q2+(l1.*sin(alpha+q0+q1))./q1+l1.*1.0./q1.^2.*(cos(alpha+q0+q1)-cos(alpha+q0))).*((l1.*(sin(alpha+q0+q1)-sin(alpha+q0)))./q1+(l0.*sin(alpha+q0))./q0-(l2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2)))./q2+l0.*1.0./q0.^2.*(cos(alpha+q0)-cos(alpha)));
et9 = -rho2.*(l2.*1.0./q2.^2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2))+(s.*cos(alpha+q0+q1+(q2.*s)./l2))./q2).*(l1.*1.0./q1.^2.*(sin(alpha+q0+q1)-sin(alpha+q0))+(l2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2)))./q2-(l1.*cos(alpha+q0+q1))./q1);
et10 = -rho2.*(l2.*1.0./q2.^2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2))-(s.*sin(alpha+q0+q1+(q2.*s)./l2))./q2).*(-(l2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2)))./q2+(l1.*sin(alpha+q0+q1))./q1+l1.*1.0./q1.^2.*(cos(alpha+q0+q1)-cos(alpha+q0)));
et11 = rho2.*(l2.*1.0./q2.^2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2))+(s.*cos(alpha+q0+q1+(q2.*s)./l2))./q2).*((l0.*cos(alpha+q0))./q0-(l2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2)))./q2-l0.*1.0./q0.^2.*(sin(alpha+q0)-sin(alpha))+(l1.*(cos(alpha+q0+q1)-cos(alpha+q0)))./q1);
et12 = -rho2.*(l2.*1.0./q2.^2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2))-(s.*sin(alpha+q0+q1+(q2.*s)./l2))./q2).*((l1.*(sin(alpha+q0+q1)-sin(alpha+q0)))./q1+(l0.*sin(alpha+q0))./q0-(l2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2)))./q2+l0.*1.0./q0.^2.*(cos(alpha+q0)-cos(alpha)));
mt1 = [rho2.*((l0.*cos(alpha+q0))./q0-(l2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2)))./q2-l0.*1.0./q0.^2.*(sin(alpha+q0)-sin(alpha))+(l1.*(cos(alpha+q0+q1)-cos(alpha+q0)))./q1).^2+rho2.*((l1.*(sin(alpha+q0+q1)-sin(alpha+q0)))./q1+(l0.*sin(alpha+q0))./q0-(l2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2)))./q2+l0.*1.0./q0.^2.*(cos(alpha+q0)-cos(alpha))).^2,et3+et4,et1+et2,et7+et8];
mt2 = [rho2.*(l1.*1.0./q1.^2.*(sin(alpha+q0+q1)-sin(alpha+q0))+(l2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2)))./q2-(l1.*cos(alpha+q0+q1))./q1).^2+rho2.*(-(l2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2)))./q2+(l1.*sin(alpha+q0+q1))./q1+l1.*1.0./q1.^2.*(cos(alpha+q0+q1)-cos(alpha+q0))).^2,et5+et6,et11+et12,et9+et10];
mt3 = [rho2.*(l2.*1.0./q2.^2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+(q2.*s)./l2))-(s.*sin(alpha+q0+q1+(q2.*s)./l2))./q2).^2+rho2.*(l2.*1.0./q2.^2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+(q2.*s)./l2))+(s.*cos(alpha+q0+q1+(q2.*s)./l2))./q2).^2];
B2_ds = reshape([mt1,mt2,mt3],3,3);
