function out1 = C12_fun(in1,in2,alpha,in4,in5)
%C12_FUN
%    OUT1 = C12_FUN(IN1,IN2,ALPHA,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Apr-2021 16:22:15

l0 = in4(1,:);
l1 = in4(2,:);
l2 = in4(3,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
qdot0 = in2(1,:);
qdot1 = in2(2,:);
qdot2 = in2(3,:);
rho1 = in5(2,:);
rho2 = in5(3,:);
t2 = cos(q0);
t3 = cos(q1);
t4 = cos(q2);
t5 = sin(q0);
t6 = sin(q1);
t7 = sin(q2);
t8 = q0+q1;
t9 = q1+q2;
t10 = l1.^2;
t11 = l1.^3;
t12 = l2.^2;
t13 = l2.^3;
t14 = q0.^2;
t15 = q1.^2;
t16 = q1.^3;
t17 = q2.^2;
t19 = q2.^3;
t20 = q1.^5;
t27 = 1.0./l1;
t28 = 1.0./l2;
t30 = l1.*q0.*1.0e+3;
t31 = l2.*q0.*1.0e+3;
t32 = l2.*q1.*1.0e+3;
t18 = t15.^2;
t21 = t17.^2;
t22 = cos(t8);
t23 = cos(t9);
t24 = q2+t8;
t25 = sin(t8);
t26 = sin(t9);
t33 = q1+t30;
t34 = q2+t32;
t35 = (q1.*t27)./1.0e+3;
t36 = (q2.*t28)./1.0e+3;
t29 = sin(t24);
t37 = sin(t35);
t38 = sin(t36);
t39 = cos(t35);
t40 = cos(t36);
t41 = t31+t34;
t42 = (t27.*t33)./1.0e+3;
t43 = (t28.*t34)./1.0e+3;
t44 = cos(t42);
t45 = cos(t43);
t46 = sin(t42);
t47 = sin(t43);
t48 = (t28.*t41)./1.0e+3;
t49 = sin(t48);
et1 = l0.*l1.*t15.*t21.*qdot1.*rho1.*2.0e+3+l0.*l1.*t15.*t21.*qdot1.*rho2.*2.0e+3-l0.*t10.*t15.*t21.*qdot1.*rho1.*2.0e+6-l1.*t14.*t15.*t21.*qdot1.*rho1+l0.*t16.*t21.*qdot0.*rho1.*t30+l0.*t16.*t21.*qdot0.*rho2.*t30+l0.*qdot1.*rho1.*t16.*t21.*t37-l0.*qdot1.*rho1.*t16.*t21.*t46-t12.*t14.*t20.*q2.*qdot2.*rho2.*2.0e+3+t13.*t14.*t20.*q2.*qdot2.*rho2.*2.0e+6-t11.*t14.*t21.*qdot1.*rho1.*t3.*4.0e+6-t13.*t14.*t20.*qdot2.*rho2.*t7.*3.0e+6-t10.*t14.*t15.*t21.*qdot0.*rho1.*2.0e+3-t10.*t14.*t15.*t21.*qdot0.*rho2.*2.0e+3+t11.*t14.*t15.*t21.*qdot0.*rho1.*2.0e+6-t10.*t14.*t15.*t21.*qdot1.*rho2.*2.0e+3+t11.*t14.*t15.*t21.*qdot1.*rho1.*1.0e+6;
et2 = qdot1.*rho1.*t11.*t14.*t21.*t39.*4.0e+6+qdot2.*rho2.*t13.*t14.*t20.*t38.*3.0e+6-l0.*l1.*l2.*t15.*t21.*qdot1.*rho2.*2.0e+6-l0.*l1.*t15.*t21.*qdot1.*rho1.*t2.*2.0e+3-l0.*l1.*t15.*t21.*qdot1.*rho2.*t2.*2.0e+3-l0.*l1.*t15.*t21.*qdot1.*rho2.*t3.*2.0e+3-l0.*l1.*t16.*t21.*qdot0.*rho1.*t5.*1.0e+3-l0.*l1.*t16.*t21.*qdot0.*rho2.*t5.*1.0e+3+l0.*l1.*t18.*t21.*qdot0.*rho2.*t3.*1.0e+3-l0.*l1.*t16.*t21.*qdot0.*rho2.*t6.*1.0e+3+l0.*l1.*t18.*t21.*qdot1.*rho2.*t3.*1.0e+3-l0.*l2.*t20.*t19.*qdot0.*rho2.*t3.*1.0e+3-l0.*l1.*t16.*t21.*qdot1.*rho2.*t6.*2.0e+3-l0.*l2.*t20.*t19.*qdot1.*rho2.*t3.*1.0e+3+l0.*l2.*t20.*t17.*qdot2.*rho2.*t6.*1.0e+3;
et3 = l1.*l2.*t14.*t16.*t19.*qdot0.*rho2.*1.0e+3+l1.*l2.*t14.*t16.*t19.*qdot1.*rho2.*2.0e+3+l1.*l2.*t14.*t18.*t17.*qdot2.*rho2.*1.0e+3+l0.*l1.*t15.*t21.*qdot1.*rho2.*t22.*2.0e+3-l0.*l1.*t18.*t21.*qdot0.*rho2.*t22.*1.0e+3+l0.*l1.*t16.*t21.*qdot0.*rho2.*t25.*1.0e+3-l0.*l1.*t18.*t21.*qdot1.*rho2.*t22.*1.0e+3+l0.*l2.*t20.*t19.*qdot0.*rho2.*t22.*1.0e+3+l0.*l1.*t16.*t21.*qdot1.*rho2.*t25.*2.0e+3+l0.*l2.*t20.*t19.*qdot1.*rho2.*t22.*1.0e+3-l0.*l2.*t20.*t17.*qdot2.*rho2.*t25.*1.0e+3+l0.*l1.*qdot0.*rho1.*t16.*t21.*t37.*1.0e+3+l0.*l1.*qdot1.*rho1.*t15.*t21.*t39.*4.0e+3-l0.*l1.*qdot1.*rho1.*t15.*t21.*t44.*4.0e+3-l0.*l1.*qdot0.*rho1.*t16.*t21.*t46.*1.0e+3+l0.*l2.*qdot2.*rho2.*t17.*t20.*t47.*1.0e+3;
et4 = l0.*t10.*q1.*t21.*qdot1.*rho1.*t6.*6.0e+6-l0.*t10.*q0.*t16.*t21.*qdot0.*rho1.*1.0e+6-l0.*t10.*q1.*t21.*qdot1.*rho1.*t25.*6.0e+6-l0.*t12.*t20.*q2.*qdot2.*rho2.*t23.*2.0e+6-l0.*q1.*qdot1.*rho1.*t10.*t21.*t37.*6.0e+6+l0.*q0.*qdot1.*rho1.*t16.*t21.*t39+l0.*q1.*qdot1.*rho1.*t10.*t21.*t46.*6.0e+6+l0.*q2.*qdot2.*rho2.*t12.*t20.*t45.*2.0e+6-l0.*t10.*t15.*t21.*qdot0.*rho1.*t3.*2.0e+6+l0.*t10.*t15.*t21.*qdot1.*rho1.*t2.*2.0e+6-l0.*t10.*t15.*t21.*qdot1.*rho1.*t3.*4.0e+6+l0.*t10.*t16.*t21.*qdot0.*rho1.*t5.*1.0e+6-l0.*t10.*t16.*t21.*qdot0.*rho1.*t6.*1.0e+6;
et5 = l0.*t10.*t16.*t21.*qdot1.*rho1.*t6.*-1.0e+6+l0.*t12.*t20.*t19.*qdot0.*rho2.*t3.*1.0e+6+l0.*t12.*t20.*t19.*qdot1.*rho2.*t3.*1.0e+6-l0.*t12.*t20.*t17.*qdot2.*rho2.*t6.*1.0e+6-l1.*t12.*t14.*t16.*t19.*qdot0.*rho2.*1.0e+6+t10.*l2.*t14.*t15.*t21.*qdot0.*rho2.*2.0e+6-l1.*t12.*t14.*t16.*t19.*qdot1.*rho2.*2.0e+6+t10.*l2.*t14.*t15.*t21.*qdot1.*rho2.*2.0e+6-l1.*t12.*t14.*t18.*t17.*qdot2.*rho2.*1.0e+6+l0.*t10.*t15.*t21.*qdot0.*rho1.*t22.*2.0e+6+l0.*t10.*t15.*t21.*qdot1.*rho1.*t22.*4.0e+6+l0.*t10.*t16.*t21.*qdot0.*rho1.*t25.*1.0e+6+l0.*t10.*t16.*t21.*qdot1.*rho1.*t25.*1.0e+6;
et6 = l0.*t12.*t20.*t19.*qdot0.*rho2.*t22.*-1.0e+6+l0.*t20.*t17.*qdot2.*rho2.*t3.*t31-l0.*t12.*t20.*t19.*qdot1.*rho2.*t22.*1.0e+6-l0.*t12.*t20.*t17.*qdot0.*rho2.*t26.*1.0e+6-l0.*t12.*t20.*t17.*qdot1.*rho2.*t26.*1.0e+6+l0.*t12.*t20.*t17.*qdot2.*rho2.*t25.*1.0e+6+l0.*t20.*t19.*qdot0.*rho2.*t6.*t31-l0.*t12.*t20.*t17.*qdot2.*rho2.*t26.*1.0e+6+l0.*t20.*t19.*qdot1.*rho2.*t6.*t31+l0.*t12.*t20.*t17.*qdot0.*rho2.*t29.*1.0e+6+l0.*t12.*t20.*t17.*qdot1.*rho2.*t29.*1.0e+6+l0.*t12.*t20.*t17.*qdot2.*rho2.*t29.*1.0e+6+l0.*qdot0.*rho1.*t10.*t15.*t21.*t39.*2.0e+6-l0.*qdot0.*rho1.*t10.*t15.*t21.*t44.*2.0e+6;
et7 = -l1.*qdot1.*rho1.*t14.*t15.*t21.*t39+l0.*qdot0.*rho2.*t12.*t17.*t20.*t47.*1.0e+6+l0.*qdot1.*rho2.*t12.*t17.*t20.*t47.*1.0e+6+l0.*qdot0.*rho1.*t16.*t21.*t30.*t39+l0.*qdot2.*rho2.*t17.*t20.*t31.*t45-t11.*t14.*q1.*t21.*qdot0.*rho1.*t6.*3.0e+6-t11.*t14.*q1.*t21.*qdot1.*rho1.*t6.*4.0e+6+t13.*t14.*t20.*q2.*qdot2.*rho2.*t4.*1.0e+6+q1.*qdot0.*rho1.*t11.*t14.*t21.*t37.*3.0e+6+q1.*qdot1.*rho1.*t10.*t14.*t21.*t37.*4.0e+3-q2.*qdot2.*rho2.*t12.*t14.*t20.*t40.*1.0e+3+t10.*t14.*t15.*t21.*qdot0.*rho2.*t3.*2.0e+3+t11.*t14.*t15.*t21.*qdot0.*rho1.*t3.*1.0e+6+t10.*t14.*t15.*t21.*qdot1.*rho2.*t3.*2.0e+3+t11.*t14.*t15.*t21.*qdot1.*rho1.*t3.*1.0e+6;
et8 = t10.*t14.*t16.*t21.*qdot0.*rho2.*t6.*1.0e+3+t10.*t14.*t16.*t21.*qdot1.*rho2.*t6.*1.0e+3-qdot0.*rho1.*t10.*t14.*t15.*t21.*t39.*1.0e+3-l0.*q2.*qdot2.*rho2.*t12.*t20.*cos(t48).*2.0e+6-l0.*l2.*qdot2.*rho2.*t17.*t20.*t49.*1.0e+3-l0.*qdot0.*rho2.*t12.*t17.*t20.*t49.*1.0e+6-l0.*qdot1.*rho2.*t12.*t17.*t20.*t49.*1.0e+6+l0.*t12.*t20.*q2.*qdot2.*rho2.*cos(t24).*2.0e+6-l0.*l1.*l2.*q0.*t16.*t21.*qdot0.*rho2.*1.0e+6+l0.*l1.*l2.*t15.*t21.*qdot1.*rho2.*t2.*2.0e+6+l0.*l1.*l2.*t15.*t21.*qdot1.*rho2.*t3.*2.0e+6+l0.*l1.*l2.*t16.*t21.*qdot0.*rho2.*t5.*1.0e+6-l0.*l1.*l2.*t18.*t21.*qdot0.*rho2.*t3.*1.0e+6;
et9 = l0.*l1.*l2.*t16.*t21.*qdot0.*rho2.*t6.*1.0e+6-l0.*l1.*l2.*t18.*t21.*qdot1.*rho2.*t3.*1.0e+6+l0.*l1.*l2.*t16.*t21.*qdot1.*rho2.*t6.*2.0e+6-l0.*l1.*l2.*t15.*t21.*qdot1.*rho2.*t22.*2.0e+6+l0.*l1.*l2.*t18.*t21.*qdot0.*rho2.*t22.*1.0e+6-l0.*l1.*l2.*t16.*t21.*qdot0.*rho2.*t25.*1.0e+6+l0.*l1.*l2.*t18.*t21.*qdot1.*rho2.*t22.*1.0e+6-l0.*l1.*l2.*t16.*t21.*qdot1.*rho2.*t25.*2.0e+6-l0.*l1.*q0.*t16.*t21.*qdot0.*rho2.*t3.*1.0e+3-l0.*l1.*q0.*t16.*t21.*qdot1.*rho2.*t3.*2.0e+3+l0.*l1.*q0.*t15.*t21.*qdot1.*rho2.*t6.*2.0e+3-l0.*l1.*q0.*t18.*t21.*qdot0.*rho2.*t6.*1.0e+3;
et10 = l0.*l1.*q0.*t18.*t21.*qdot1.*rho2.*t6.*-1.0e+3-l0.*l1.*q0.*qdot1.*rho1.*t15.*t21.*t37.*4.0e+3-l1.*l2.*t14.*t16.*t19.*qdot0.*rho2.*t3.*1.0e+3-l1.*l2.*t14.*t18.*t17.*qdot2.*rho2.*t3.*1.0e+3-l1.*l2.*t14.*t15.*t19.*qdot1.*rho2.*t6.*2.0e+3-l1.*l2.*t14.*t18.*t19.*qdot0.*rho2.*t6.*1.0e+3-l1.*l2.*t14.*t18.*t19.*qdot1.*rho2.*t6.*1.0e+3+l1.*l2.*qdot2.*rho2.*t14.*t17.*t18.*t40.*1.0e+3-l1.*l2.*qdot2.*rho2.*t14.*t17.*t18.*t45.*1.0e+3+l0.*t10.*q0.*q1.*t21.*qdot1.*rho1.*t3.*6.0e+6+l0.*t12.*q0.*t20.*q2.*qdot2.*rho2.*t26.*2.0e+6-l0.*q0.*q1.*qdot1.*rho1.*t10.*t21.*t39.*6.0e+6-l0.*q0.*q2.*qdot2.*rho2.*t12.*t20.*t47.*2.0e+6;
et11 = l0.*t10.*q0.*t16.*t21.*qdot0.*rho1.*t3.*-1.0e+6-l0.*t10.*q0.*t16.*t21.*qdot1.*rho1.*t3.*1.0e+6+l0.*t10.*q0.*t15.*t21.*qdot0.*rho1.*t6.*2.0e+6+l0.*t10.*q0.*t15.*t21.*qdot1.*rho1.*t6.*4.0e+6-l0.*t12.*q0.*t20.*t17.*qdot2.*rho2.*t3.*1.0e+6+l1.*t12.*t14.*t18.*q2.*qdot2.*rho2.*t7.*2.0e+6-l0.*t12.*q0.*t20.*t19.*qdot0.*rho2.*t6.*1.0e+6-l0.*t12.*q0.*t20.*t19.*qdot1.*rho2.*t6.*1.0e+6-l0.*t12.*q0.*t20.*t17.*qdot0.*rho2.*t23.*1.0e+6-l0.*t12.*q0.*t20.*t17.*qdot1.*rho2.*t23.*1.0e+6-l0.*t12.*q0.*t20.*t17.*qdot2.*rho2.*t23.*1.0e+6;
et12 = l1.*t12.*t14.*t18.*q2.*qdot2.*rho2.*t26.*-2.0e+6-l0.*q0.*qdot0.*rho1.*t10.*t15.*t21.*t37.*2.0e+6-l1.*q2.*qdot2.*rho2.*t12.*t14.*t18.*t38.*2.0e+6+l0.*q0.*qdot0.*rho2.*t12.*t17.*t20.*t45.*1.0e+6+l0.*q0.*qdot1.*rho2.*t12.*t17.*t20.*t45.*1.0e+6+l1.*q2.*qdot2.*rho2.*t12.*t14.*t18.*t47.*2.0e+6-l1.*t12.*t14.*t15.*t17.*qdot1.*rho2.*t4.*2.0e+6+l1.*t12.*t14.*t16.*t19.*qdot0.*rho2.*t3.*1.0e+6-t10.*l2.*t14.*t15.*t21.*qdot0.*rho2.*t3.*2.0e+6-t10.*l2.*t14.*t15.*t21.*qdot1.*rho2.*t3.*2.0e+6+l1.*t12.*t14.*t16.*t17.*qdot0.*rho2.*t7.*1.0e+6+l1.*t12.*t14.*t18.*t17.*qdot2.*rho2.*t3.*1.0e+6;
et13 = l1.*t12.*t14.*t15.*t19.*qdot1.*rho2.*t6.*2.0e+6+l1.*t12.*t14.*t16.*t17.*qdot1.*rho2.*t7.*2.0e+6-l1.*t12.*t14.*t18.*t17.*qdot2.*rho2.*t4.*1.0e+6-t10.*l2.*t14.*t16.*t21.*qdot0.*rho2.*t6.*1.0e+6+l1.*t12.*t14.*t18.*t19.*qdot0.*rho2.*t6.*1.0e+6-t10.*l2.*t14.*t16.*t21.*qdot1.*rho2.*t6.*1.0e+6+l1.*t12.*t14.*t18.*t19.*qdot1.*rho2.*t6.*1.0e+6+l1.*t12.*t14.*t15.*t17.*qdot1.*rho2.*t23.*2.0e+6+l1.*t12.*t14.*t18.*t17.*qdot0.*rho2.*t23.*1.0e+6-l1.*t12.*t14.*t16.*t17.*qdot0.*rho2.*t26.*1.0e+6+l1.*t12.*t14.*t18.*t17.*qdot1.*rho2.*t23.*1.0e+6+l1.*t12.*t14.*t18.*t17.*qdot2.*rho2.*t23.*1.0e+6;
et14 = l1.*qdot0.*rho2.*t12.*t14.*t16.*t17.*t38.*-1.0e+6-l1.*qdot1.*rho2.*t12.*t14.*t16.*t17.*t38.*2.0e+6+l1.*qdot1.*rho2.*t12.*t14.*t15.*t17.*t40.*2.0e+6-l1.*qdot1.*rho2.*t12.*t14.*t15.*t17.*t45.*2.0e+6+l1.*qdot0.*rho2.*t12.*t14.*t16.*t17.*t47.*1.0e+6-l1.*qdot0.*rho2.*t12.*t14.*t17.*t18.*t45.*1.0e+6-l1.*qdot1.*rho2.*t12.*t14.*t17.*t18.*t45.*1.0e+6+l0.*l1.*l2.*q0.*t16.*t21.*qdot0.*rho2.*t3.*1.0e+6+l0.*l1.*l2.*q0.*t16.*t21.*qdot1.*rho2.*t3.*2.0e+6-l0.*l1.*l2.*q0.*t15.*t21.*qdot1.*rho2.*t6.*2.0e+6+l0.*l1.*l2.*q0.*t18.*t21.*qdot0.*rho2.*t6.*1.0e+6;
et15 = l0.*l1.*l2.*q0.*t18.*t21.*qdot1.*rho2.*t6.*1.0e+6;
if ((q1 ~= 0.0) & (q2 ~= 0.0))
    out1 = ((et1+et2+et3+et4+et5+et6+et7+et8+et9+et10+et11+et12+et13+et14+et15).*(-1.0e-6))./(t14.*t20.*t21);
else
    out1 = NaN;
end
