function out1 = C13_fun(in1,in2,alpha,in4,in5)
%C13_FUN
%    OUT1 = C13_FUN(IN1,IN2,ALPHA,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Apr-2021 16:22:16

l0 = in4(1,:);
l1 = in4(2,:);
l2 = in4(3,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
qdot0 = in2(1,:);
qdot1 = in2(2,:);
qdot2 = in2(3,:);
rho2 = in5(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q0+q1;
t7 = q1+q2;
t8 = l2.^2;
t9 = l2.^3;
t10 = q0.^2;
t11 = q2.^2;
t12 = q2.^3;
t18 = 1.0./l2;
t21 = l2.*q0.*1.0e+3;
t22 = l2.*q1.*1.0e+3;
t13 = cos(t6);
t14 = cos(t7);
t15 = q2+t6;
t16 = sin(t6);
t17 = sin(t7);
t23 = q2+t22;
t24 = (q2.*t18)./1.0e+3;
t19 = cos(t15);
t20 = sin(t15);
t25 = sin(t24);
t26 = cos(t24);
t27 = t21+t23;
t28 = (t18.*t23)./1.0e+3;
t29 = cos(t28);
t30 = sin(t28);
t31 = (t18.*t27)./1.0e+3;
t32 = cos(t31);
t33 = sin(t31);
et1 = l1.*l2.*t10.*t12.*qdot0.*rho2.*1.0e+3+l1.*l2.*t10.*t12.*qdot1.*rho2.*1.0e+3-l2.*t10.*q1.*t11.*qdot2.*rho2+l0.*q1.*qdot2.*rho2.*t12.*t30-l1.*t8.*t10.*t12.*qdot0.*rho2.*1.0e+6-l1.*t8.*t10.*t12.*qdot1.*rho2.*1.0e+6+l0.*t12.*qdot0.*rho2.*t4.*t22+l0.*t12.*qdot1.*rho2.*t4.*t22+l1.*qdot2.*rho2.*t10.*t12.*t26-l1.*qdot2.*rho2.*t10.*t12.*t29+l0.*qdot0.*rho2.*t12.*t22.*t30+l0.*qdot1.*rho2.*t12.*t22.*t30-t9.*t10.*q1.*qdot2.*rho2.*t3.*4.0e+6-t8.*t10.*q1.*t11.*qdot0.*rho2.*2.0e+3-t8.*t10.*q1.*t11.*qdot1.*rho2.*2.0e+3+t9.*t10.*q1.*t11.*qdot0.*rho2.*2.0e+6+t9.*t10.*q1.*t11.*qdot1.*rho2.*2.0e+6+t9.*t10.*q1.*t11.*qdot2.*rho2.*1.0e+6;
et2 = q1.*qdot2.*rho2.*t9.*t10.*t26.*4.0e+6-l0.*q1.*qdot2.*rho2.*t12.*t33+l0.*l2.*q1.*t11.*qdot2.*rho2.*t2.*2.0e+3-l0.*l2.*q1.*t11.*qdot2.*rho2.*t13.*2.0e+3-l0.*l2.*q1.*t12.*qdot0.*rho2.*t16.*1.0e+3-l0.*l2.*q1.*t12.*qdot1.*rho2.*t16.*1.0e+3+l0.*l2.*q1.*qdot2.*rho2.*t11.*t29.*4.0e+3-l1.*l2.*t10.*t12.*qdot0.*rho2.*t2.*1.0e+3-l1.*l2.*t10.*t12.*qdot1.*rho2.*t2.*1.0e+3+l1.*l2.*t10.*t11.*qdot2.*rho2.*t4.*2.0e+3+l1.*l2.*qdot0.*rho2.*t10.*t12.*t26.*1.0e+3-l1.*l2.*qdot2.*rho2.*t10.*t11.*t25.*4.0e+3+l1.*l2.*qdot1.*rho2.*t10.*t12.*t26.*1.0e+3-l1.*l2.*qdot0.*rho2.*t10.*t12.*t29.*1.0e+3-l1.*l2.*qdot1.*rho2.*t10.*t12.*t29.*1.0e+3+l1.*l2.*qdot2.*rho2.*t10.*t11.*t30.*4.0e+3;
et3 = l0.*t8.*q1.*q2.*qdot2.*rho2.*t17.*6.0e+6-l0.*t8.*q1.*q2.*qdot2.*rho2.*t20.*6.0e+6-l0.*q1.*q2.*qdot2.*rho2.*t8.*t30.*6.0e+6+l0.*q0.*q1.*qdot2.*rho2.*t12.*t29-l0.*t8.*q1.*t11.*qdot2.*rho2.*t2.*2.0e+6-l0.*t8.*q1.*t12.*qdot0.*rho2.*t4.*1.0e+6-l0.*t8.*q1.*t12.*qdot1.*rho2.*t4.*1.0e+6+l1.*t8.*t10.*q2.*qdot2.*rho2.*t3.*6.0e+6-l0.*t8.*q1.*t11.*qdot0.*rho2.*t14.*2.0e+6-l0.*t8.*q1.*t11.*qdot1.*rho2.*t14.*2.0e+6+l0.*t8.*q1.*t11.*qdot2.*rho2.*t13.*2.0e+6+l0.*q1.*t12.*qdot0.*rho2.*t2.*t21-l0.*t8.*q1.*t11.*qdot2.*rho2.*t14.*4.0e+6+l0.*q1.*t12.*qdot1.*rho2.*t2.*t21;
et4 = l0.*t8.*q1.*t12.*qdot0.*rho2.*t16.*1.0e+6-l1.*t8.*t10.*q2.*qdot2.*rho2.*t14.*6.0e+6-l0.*t8.*q1.*t12.*qdot0.*rho2.*t17.*1.0e+6+l0.*t8.*q1.*t12.*qdot1.*rho2.*t16.*1.0e+6+l0.*t8.*q1.*t11.*qdot0.*rho2.*t19.*2.0e+6-l0.*t8.*q1.*t12.*qdot1.*rho2.*t17.*1.0e+6+l0.*t8.*q1.*t11.*qdot1.*rho2.*t19.*2.0e+6-l0.*t8.*q1.*t12.*qdot2.*rho2.*t17.*1.0e+6+l0.*t8.*q1.*t11.*qdot2.*rho2.*t19.*4.0e+6+l0.*t8.*q1.*t12.*qdot0.*rho2.*t20.*1.0e+6+l0.*t8.*q1.*t12.*qdot1.*rho2.*t20.*1.0e+6+l0.*t8.*q1.*t12.*qdot2.*rho2.*t20.*1.0e+6+l0.*q1.*qdot0.*rho2.*t8.*t11.*t29.*2.0e+6;
et5 = l1.*q2.*qdot2.*rho2.*t8.*t10.*t26.*-6.0e+6+l0.*q1.*qdot1.*rho2.*t8.*t11.*t29.*2.0e+6+l1.*q2.*qdot2.*rho2.*t8.*t10.*t29.*6.0e+6-l2.*q1.*qdot2.*rho2.*t10.*t11.*t26+l0.*q1.*qdot0.*rho2.*t12.*t21.*t29+l0.*q1.*qdot1.*rho2.*t12.*t21.*t29+l1.*t8.*t10.*t12.*qdot0.*rho2.*t2.*1.0e+6-l1.*t8.*t10.*t12.*qdot0.*rho2.*t3.*1.0e+6+l1.*t8.*t10.*t12.*qdot1.*rho2.*t2.*1.0e+6+l1.*t8.*t10.*t11.*qdot0.*rho2.*t5.*2.0e+6-l1.*t8.*t10.*t12.*qdot1.*rho2.*t3.*1.0e+6+l1.*t8.*t10.*t11.*qdot1.*rho2.*t5.*2.0e+6-l1.*t8.*t10.*t11.*qdot2.*rho2.*t4.*2.0e+6-l1.*t8.*t10.*t12.*qdot2.*rho2.*t3.*1.0e+6;
et6 = l1.*t8.*t10.*t11.*qdot2.*rho2.*t5.*4.0e+6+l1.*t8.*t10.*t12.*qdot0.*rho2.*t14.*1.0e+6+l1.*t8.*t10.*t12.*qdot1.*rho2.*t14.*1.0e+6-l1.*t8.*t10.*t11.*qdot0.*rho2.*t17.*2.0e+6+l1.*t8.*t10.*t12.*qdot2.*rho2.*t14.*1.0e+6-l1.*t8.*t10.*t11.*qdot1.*rho2.*t17.*2.0e+6-l1.*t8.*t10.*t11.*qdot2.*rho2.*t17.*4.0e+6-l1.*qdot0.*rho2.*t8.*t10.*t11.*t25.*2.0e+6-l1.*qdot1.*rho2.*t8.*t10.*t11.*t25.*2.0e+6+l1.*qdot0.*rho2.*t8.*t10.*t11.*t30.*2.0e+6+l1.*qdot1.*rho2.*t8.*t10.*t11.*t30.*2.0e+6-t9.*t10.*q1.*q2.*qdot0.*rho2.*t5.*3.0e+6;
et7 = t9.*t10.*q1.*q2.*qdot1.*rho2.*t5.*-3.0e+6-t9.*t10.*q1.*q2.*qdot2.*rho2.*t5.*4.0e+6+q1.*q2.*qdot0.*rho2.*t9.*t10.*t25.*3.0e+6+q1.*q2.*qdot1.*rho2.*t9.*t10.*t25.*3.0e+6+q1.*q2.*qdot2.*rho2.*t8.*t10.*t25.*4.0e+3+t9.*t10.*q1.*t11.*qdot0.*rho2.*t3.*1.0e+6+t9.*t10.*q1.*t11.*qdot1.*rho2.*t3.*1.0e+6+t9.*t10.*q1.*t11.*qdot2.*rho2.*t3.*1.0e+6-q1.*qdot0.*rho2.*t8.*t10.*t11.*t26.*1.0e+3-q1.*qdot1.*rho2.*t8.*t10.*t11.*t26.*1.0e+3-l0.*l2.*q1.*qdot2.*rho2.*t11.*t32.*4.0e+3-l0.*q1.*qdot0.*rho2.*t8.*t11.*t32.*2.0e+6-l0.*q1.*qdot1.*rho2.*t8.*t11.*t32.*2.0e+6;
et8 = l0.*l2.*q1.*qdot0.*rho2.*t12.*t33.*-1.0e+3-l0.*l2.*q1.*qdot1.*rho2.*t12.*t33.*1.0e+3+l0.*q1.*q2.*qdot2.*rho2.*t8.*t33.*6.0e+6-l0.*l2.*q0.*q1.*t11.*qdot2.*rho2.*t4.*2.0e+3-l0.*l2.*q0.*q1.*qdot2.*rho2.*t11.*t30.*4.0e+3+l0.*t8.*q0.*q1.*q2.*qdot2.*rho2.*t14.*6.0e+6-l0.*q0.*q1.*q2.*qdot2.*rho2.*t8.*t29.*6.0e+6-l0.*t8.*q0.*q1.*t12.*qdot0.*rho2.*t2.*1.0e+6-l0.*t8.*q0.*q1.*t12.*qdot1.*rho2.*t2.*1.0e+6+l0.*t8.*q0.*q1.*t11.*qdot2.*rho2.*t4.*2.0e+6-l0.*t8.*q0.*q1.*t12.*qdot0.*rho2.*t14.*1.0e+6-l0.*t8.*q0.*q1.*t12.*qdot1.*rho2.*t14.*1.0e+6;
et9 = l0.*t8.*q0.*q1.*t11.*qdot0.*rho2.*t17.*2.0e+6-l0.*t8.*q0.*q1.*t12.*qdot2.*rho2.*t14.*1.0e+6+l0.*t8.*q0.*q1.*t11.*qdot1.*rho2.*t17.*2.0e+6+l0.*t8.*q0.*q1.*t11.*qdot2.*rho2.*t17.*4.0e+6-l0.*q0.*q1.*qdot0.*rho2.*t8.*t11.*t30.*2.0e+6-l0.*q0.*q1.*qdot1.*rho2.*t8.*t11.*t30.*2.0e+6;
if ((q1 ~= 0.0) & (q2 ~= 0.0))
    out1 = (1.0./q2.^5.*(et1+et2+et3+et4+et5+et6+et7+et8+et9).*(-1.0e-6))./(q1.*t10);
else
    out1 = NaN;
end
