function out1 = C21_fun(in1,in2,alpha,in4,in5)
%C21_FUN
%    OUT1 = C21_FUN(IN1,IN2,ALPHA,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Apr-2021 16:22:17

l0 = in4(1,:);
l1 = in4(2,:);
l2 = in4(3,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
qdot0 = in2(1,:);
qdot2 = in2(3,:);
rho1 = in5(2,:);
rho2 = in5(3,:);
t2 = cos(q0);
t3 = cos(q1);
t4 = cos(q2);
t5 = sin(q1);
t6 = sin(q2);
t7 = q0+q1;
t8 = q1+q2;
t9 = l1.^2;
t10 = l1.^3;
t11 = l2.^2;
t12 = l2.^3;
t13 = q0.^2;
t14 = q0.^3;
t15 = q1.^2;
t16 = q1.^3;
t17 = q2.^2;
t19 = q2.^3;
t25 = 1.0./l1;
t26 = 1.0./l2;
t27 = l1.*q0.*1.0e+3;
t28 = l2.*q1.*1.0e+3;
t18 = t15.^2;
t20 = t17.^2;
t21 = cos(t7);
t22 = cos(t8);
t23 = sin(t7);
t24 = sin(t8);
t29 = q1+t27;
t30 = q2+t28;
t31 = (q1.*t25)./1.0e+3;
t32 = (q2.*t26)./1.0e+3;
t33 = sin(t31);
t34 = sin(t32);
t35 = cos(t31);
t36 = cos(t32);
t37 = (t25.*t29)./1.0e+3;
t38 = (t26.*t30)./1.0e+3;
t39 = cos(t38);
t40 = sin(t38);
et1 = l0.*l1.*t15.*t20.*qdot0.*rho1.*2.0+l0.*l1.*t15.*t20.*qdot0.*rho2.*2.0-l0.*t9.*t15.*t20.*qdot0.*rho1.*2.0e+3+t9.*t14.*q1.*t20.*qdot0.*rho1.*2.0+t9.*t14.*q1.*t20.*qdot0.*rho2.*2.0-t10.*t14.*q1.*t20.*qdot0.*rho1.*2.0e+3-t11.*t14.*t18.*q2.*qdot2.*rho2.*2.0+t12.*t14.*t18.*q2.*qdot2.*rho2.*2.0e+3+t10.*t14.*t20.*qdot0.*rho1.*t5.*3.0e+3-t12.*t14.*t18.*qdot2.*rho2.*t6.*3.0e+3-qdot0.*rho1.*t10.*t14.*t20.*t33.*3.0e+3+qdot2.*rho2.*t12.*t14.*t18.*t34.*3.0e+3-l0.*qdot0.*rho2.*t11.*t17.*t18.*cos((t26.*(t30+l2.*q0.*1.0e+3))./1.0e+3).*2.0e+3-l0.*l1.*l2.*t15.*t20.*qdot0.*rho2.*2.0e+3-l0.*l1.*t15.*t20.*qdot0.*rho1.*t2.*2.0-l0.*l1.*t15.*t20.*qdot0.*rho2.*t2.*2.0-l0.*l1.*t15.*t20.*qdot0.*rho2.*t3.*2.0;
et2 = l0.*l1.*t16.*t20.*qdot0.*rho2.*t5.*-2.0+l0.*l2.*t18.*t19.*qdot0.*rho2.*t5.*2.0-l0.*l1.*t13.*t15.*t20.*qdot0.*rho1-l0.*l1.*t13.*t15.*t20.*qdot0.*rho2-l1.*l2.*t14.*t15.*t19.*qdot0.*rho2+l1.*l2.*t14.*t16.*t17.*qdot2.*rho2+l0.*l1.*t15.*t20.*qdot0.*rho2.*t21.*2.0+l0.*l1.*t16.*t20.*qdot0.*rho2.*t23.*2.0-l0.*l2.*t18.*t19.*qdot0.*rho2.*t23.*2.0+l0.*l1.*qdot0.*rho1.*t15.*t20.*t35.*2.0+l0.*t9.*q1.*t20.*qdot0.*rho1.*t5.*4.0e+3-t9.*l2.*t14.*q1.*t20.*qdot0.*rho2.*2.0e+3-l0.*t9.*q1.*t20.*qdot0.*rho1.*t23.*4.0e+3-l0.*q1.*qdot0.*rho1.*t9.*t20.*t33.*4.0e+3+l0.*t9.*t15.*t20.*qdot0.*rho1.*t2.*2.0e+3-l0.*t9.*t15.*t20.*qdot0.*rho1.*t3.*2.0e+3-l0.*t11.*t18.*t19.*qdot0.*rho2.*t5.*2.0e+3+l0.*t9.*t13.*t15.*t20.*qdot0.*rho1.*1.0e+3;
et3 = l1.*t11.*t14.*t15.*t19.*qdot0.*rho2.*1.0e+3-l1.*t11.*t14.*t16.*t17.*qdot2.*rho2.*1.0e+3+l0.*t9.*t15.*t20.*qdot0.*rho1.*t21.*2.0e+3-l0.*t11.*t18.*t17.*qdot0.*rho2.*t22.*2.0e+3+l0.*t11.*t18.*t19.*qdot0.*rho2.*t23.*2.0e+3+l0.*qdot0.*rho2.*t11.*t17.*t18.*t39.*2.0e+3-t9.*t14.*q1.*t20.*qdot0.*rho2.*t3.*2.0-t10.*t14.*q1.*t20.*qdot0.*rho1.*t3.*1.0e+3+t12.*t14.*t18.*q2.*qdot2.*rho2.*t4.*1.0e+3+q1.*qdot0.*rho1.*t9.*t14.*t20.*t35-q2.*qdot2.*rho2.*t11.*t14.*t18.*t36-t9.*t14.*t15.*t20.*qdot0.*rho2.*t5+l0.*t11.*t18.*t17.*qdot0.*rho2.*cos(q2+t7).*2.0e+3-l0.*l1.*qdot0.*rho1.*t15.*t20.*cos(t37).*2.0+l0.*q1.*qdot0.*rho1.*t9.*t20.*sin(t37).*4.0e+3+l0.*l1.*l2.*t15.*t20.*qdot0.*rho2.*t2.*2.0e+3;
et4 = l0.*l1.*l2.*t15.*t20.*qdot0.*rho2.*t3.*2.0e+3+l0.*l1.*l2.*t16.*t20.*qdot0.*rho2.*t5.*2.0e+3+l0.*l1.*l2.*t13.*t15.*t20.*qdot0.*rho2.*1.0e+3-l0.*l1.*l2.*t15.*t20.*qdot0.*rho2.*t21.*2.0e+3-l0.*l1.*l2.*t16.*t20.*qdot0.*rho2.*t23.*2.0e+3-l0.*l1.*q0.*t16.*t20.*qdot0.*rho2.*t3.*2.0+l0.*l1.*q0.*t15.*t20.*qdot0.*rho2.*t5.*2.0+l0.*l2.*q0.*t18.*t19.*qdot0.*rho2.*t3.*2.0-l0.*l1.*q0.*qdot0.*rho1.*t15.*t20.*t33.*2.0+l0.*l1.*t13.*t15.*t20.*qdot0.*rho2.*t3+l1.*l2.*t14.*t15.*t19.*qdot0.*rho2.*t3+l0.*l1.*t13.*t16.*t20.*qdot0.*rho2.*t5-l1.*l2.*t14.*t15.*t17.*qdot2.*rho2.*t5-l0.*l2.*t13.*t18.*t19.*qdot0.*rho2.*t5+l1.*l2.*t14.*t16.*t19.*qdot0.*rho2.*t5-l0.*l1.*qdot0.*rho1.*t13.*t15.*t20.*t35+l1.*l2.*qdot2.*rho2.*t14.*t15.*t17.*t34+l1.*l2.*qdot2.*rho2.*t14.*t16.*t17.*t36;
et5 = -l1.*l2.*qdot2.*rho2.*t14.*t15.*t17.*t40+l0.*t9.*q0.*q1.*t20.*qdot0.*rho1.*t3.*4.0e+3-l0.*q0.*q1.*qdot0.*rho1.*t9.*t20.*t35.*4.0e+3-l0.*t9.*t13.*q1.*t20.*qdot0.*rho1.*t5.*2.0e+3+l0.*t9.*q0.*t15.*t20.*qdot0.*rho1.*t5.*2.0e+3-l1.*t11.*t14.*t15.*q2.*qdot2.*rho2.*t4.*2.0e+3+t9.*l2.*t14.*q1.*t20.*qdot0.*rho2.*t3.*2.0e+3-l0.*t11.*q0.*t18.*t19.*qdot0.*rho2.*t3.*2.0e+3+l1.*t11.*t14.*t16.*q2.*qdot2.*rho2.*t6.*2.0e+3+l1.*t11.*t14.*t15.*q2.*qdot2.*rho2.*t22.*2.0e+3+l0.*t11.*q0.*t18.*t17.*qdot0.*rho2.*t24.*2.0e+3+l0.*q1.*qdot0.*rho1.*t9.*t13.*t20.*t33.*2.0e+3-l1.*q2.*qdot2.*rho2.*t11.*t14.*t16.*t34.*2.0e+3+l1.*q2.*qdot2.*rho2.*t11.*t14.*t15.*t36.*2.0e+3-l1.*q2.*qdot2.*rho2.*t11.*t14.*t15.*t39.*2.0e+3;
et6 = l0.*q0.*qdot0.*rho2.*t11.*t17.*t18.*t40.*-2.0e+3+l0.*t9.*t13.*t15.*t20.*qdot0.*rho1.*t3.*1.0e+3-l1.*t11.*t14.*t15.*t19.*qdot0.*rho2.*t3.*1.0e+3-l1.*t11.*t14.*t15.*t17.*qdot0.*rho2.*t6.*1.0e+3+l1.*t11.*t14.*t15.*t17.*qdot2.*rho2.*t5.*1.0e+3-l1.*t11.*t14.*t16.*t17.*qdot2.*rho2.*t4.*1.0e+3+t9.*l2.*t14.*t15.*t20.*qdot0.*rho2.*t5.*1.0e+3+l0.*t11.*t13.*t18.*t19.*qdot0.*rho2.*t5.*1.0e+3-l1.*t11.*t14.*t15.*t17.*qdot2.*rho2.*t6.*1.0e+3-l1.*t11.*t14.*t16.*t19.*qdot0.*rho2.*t5.*1.0e+3+l0.*t11.*t13.*t18.*t17.*qdot0.*rho2.*t22.*1.0e+3-l1.*t11.*t14.*t16.*t17.*qdot0.*rho2.*t22.*1.0e+3+l1.*t11.*t14.*t15.*t17.*qdot0.*rho2.*t24.*1.0e+3+l1.*t11.*t14.*t15.*t17.*qdot2.*rho2.*t24.*1.0e+3;
et7 = l1.*qdot0.*rho2.*t11.*t14.*t15.*t17.*t34.*1.0e+3-l0.*qdot0.*rho2.*t11.*t13.*t17.*t18.*t39.*1.0e+3-l1.*qdot0.*rho2.*t11.*t14.*t15.*t17.*t40.*1.0e+3+l1.*qdot0.*rho2.*t11.*t14.*t16.*t17.*t39.*1.0e+3+l0.*l1.*l2.*q0.*t16.*t20.*qdot0.*rho2.*t3.*2.0e+3-l0.*l1.*l2.*q0.*t15.*t20.*qdot0.*rho2.*t5.*2.0e+3-l0.*l1.*l2.*t13.*t15.*t20.*qdot0.*rho2.*t3.*1.0e+3-l0.*l1.*l2.*t13.*t16.*t20.*qdot0.*rho2.*t5.*1.0e+3;
if ((q1 ~= 0.0) & (q2 ~= 0.0))
    out1 = ((et1+et2+et3+et4+et5+et6+et7).*(-1.0./1.0e+3))./(t14.*t18.*t20);
else
    out1 = NaN;
end
