function out1 = C22_fun(in1,in2,alpha,in4,in5)
%C22_FUN
%    OUT1 = C22_FUN(IN1,IN2,ALPHA,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Apr-2021 16:22:18

l1 = in4(2,:);
l2 = in4(3,:);
q1 = in1(2,:);
q2 = in1(3,:);
qdot1 = in2(2,:);
qdot2 = in2(3,:);
rho1 = in5(2,:);
rho2 = in5(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q1+q2;
t7 = l1.^2;
t8 = l1.^3;
t9 = l2.^2;
t10 = l2.^3;
t11 = q1.^2;
t12 = q1.^3;
t13 = q2.^2;
t15 = q2.^3;
t16 = q1.^5;
t21 = 1.0./l1;
t22 = 1.0./l2;
t23 = l2.*q1.*1.0e+3;
t14 = t11.^2;
t17 = t13.^2;
t18 = t11.^3;
t19 = cos(t6);
t20 = sin(t6);
t24 = q2+t23;
t25 = (q1.*t21)./1.0e+3;
t26 = (q2.*t22)./1.0e+3;
t27 = sin(t25);
t28 = sin(t26);
t29 = cos(t26);
t30 = (t22.*t24)./1.0e+3;
t31 = cos(t30);
t32 = sin(t30);
et1 = t12.*t17.*qdot1.*rho1+t7.*q1.*t17.*qdot1.*rho1.*1.2e+7+t7.*q1.*t17.*qdot1.*rho2.*1.2e+7-t8.*q1.*t17.*qdot1.*rho1.*1.2e+10+t9.*t18.*q2.*qdot2.*rho2.*6.0e+6-t10.*t18.*q2.*qdot2.*rho2.*6.0e+9+t8.*t17.*qdot1.*rho1.*t4.*3.0e+10+t10.*t18.*qdot2.*rho2.*t5.*9.0e+9+t7.*t12.*t17.*qdot1.*rho2.*3.0e+6-t8.*t12.*t17.*qdot1.*rho1.*1.0e+9-qdot1.*rho1.*t8.*t17.*t27.*3.0e+10-qdot2.*rho2.*t10.*t18.*t28.*9.0e+9-l1.*l2.*t14.*t15.*qdot1.*rho2.*3.0e+6;
et2 = l1.*l2.*t16.*t13.*qdot2.*rho2.*-3.0e+6-t7.*l2.*q1.*t17.*qdot1.*rho2.*1.2e+10-t7.*l2.*t12.*t17.*qdot1.*rho2.*3.0e+9+l1.*t9.*t14.*t15.*qdot1.*rho2.*3.0e+9+l1.*t9.*t16.*t13.*qdot2.*rho2.*3.0e+9+l1.*qdot1.*rho1.*t11.*t17.*t27.*3.0e+3-t7.*q1.*t17.*qdot1.*rho2.*t2.*1.2e+7-t8.*q1.*t17.*qdot1.*rho1.*t2.*1.8e+10-t10.*t18.*q2.*qdot2.*rho2.*t3.*3.0e+9+q2.*qdot2.*rho2.*t9.*t18.*t29.*3.0e+6+t7.*t12.*t17.*qdot1.*rho2.*t2.*3.0e+6-t7.*t11.*t17.*qdot1.*rho2.*t4.*1.2e+7;
et3 = t8.*t11.*t17.*qdot1.*rho1.*t4.*-3.0e+9+q1.*qdot1.*rho1.*t7.*t17.*cos(t25).*1.8e+7+l1.*l2.*t12.*t15.*qdot1.*rho2.*t4.*6.0e+6-l1.*l2.*t14.*t15.*qdot1.*rho2.*t2.*3.0e+6+l1.*l2.*t14.*t13.*qdot2.*rho2.*t4.*3.0e+6-l1.*l2.*qdot2.*rho2.*t13.*t14.*t28.*3.0e+6-l1.*l2.*qdot2.*rho2.*t13.*t16.*t29.*3.0e+6+t7.*l2.*q1.*t17.*qdot1.*rho2.*t2.*1.2e+10+l1.*t9.*t14.*q2.*qdot2.*rho2.*t3.*6.0e+9-l1.*t9.*t16.*q2.*qdot2.*rho2.*t5.*6.0e+9-l1.*t9.*t14.*q2.*qdot2.*rho2.*t19.*6.0e+9;
et4 = l1.*q2.*qdot2.*rho2.*t9.*t14.*t29.*-6.0e+9+l1.*q2.*qdot2.*rho2.*t9.*t16.*t28.*6.0e+9+l1.*t9.*t12.*t13.*qdot1.*rho2.*t3.*6.0e+9-t7.*l2.*t12.*t17.*qdot1.*rho2.*t2.*3.0e+9-l1.*t9.*t12.*t15.*qdot1.*rho2.*t4.*6.0e+9+l1.*t9.*t14.*t15.*qdot1.*rho2.*t2.*3.0e+9+t7.*l2.*t11.*t17.*qdot1.*rho2.*t4.*1.2e+10-l1.*t9.*t14.*t13.*qdot1.*rho2.*t5.*3.0e+9-l1.*t9.*t14.*t13.*qdot2.*rho2.*t4.*3.0e+9+l1.*t9.*t14.*t13.*qdot2.*rho2.*t5.*3.0e+9;
et5 = l1.*t9.*t16.*t13.*qdot2.*rho2.*t3.*3.0e+9-l1.*t9.*t12.*t13.*qdot1.*rho2.*t19.*6.0e+9-l1.*t9.*t14.*t13.*qdot1.*rho2.*t20.*3.0e+9-l1.*t9.*t14.*t13.*qdot2.*rho2.*t20.*3.0e+9-l1.*qdot1.*rho2.*t9.*t12.*t13.*t29.*6.0e+9+l1.*qdot1.*rho2.*t9.*t13.*t14.*t28.*3.0e+9+l1.*q2.*qdot2.*rho2.*t9.*t14.*t31.*6.0e+9+l1.*qdot1.*rho2.*t9.*t12.*t13.*t31.*6.0e+9+l1.*l2.*qdot2.*rho2.*t13.*t14.*t32.*3.0e+6+l1.*qdot1.*rho2.*t9.*t13.*t14.*t32.*3.0e+9;
if ((q1 ~= 0.0) & (q2 ~= 0.0))
    out1 = (et1+et2+et3+et4+et5)./(t17.*t18.*3.0e+9);
else
    out1 = NaN;
end
