function out1 = C31_fun(in1,in2,alpha,in4,in5)
%C31_FUN
%    OUT1 = C31_FUN(IN1,IN2,ALPHA,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Apr-2021 16:22:20

l0 = in4(1,:);
l1 = in4(2,:);
l2 = in4(3,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
qdot0 = in2(1,:);
qdot1 = in2(2,:);
rho2 = in5(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q0+q1;
t7 = q1+q2;
t8 = l2.^2;
t9 = q0.^2;
t10 = q0.^3;
t11 = q1.^2;
t12 = q2.^2;
t17 = 1.0./l2;
t18 = l2.*q0.*1.0e+3;
t19 = l2.*q1.*1.0e+3;
t13 = cos(t6);
t14 = cos(t7);
t15 = q2+t6;
t16 = sin(t7);
t20 = q2+t19;
t21 = (q2.*t17)./1.0e+3;
t22 = sin(t21);
t23 = cos(t21);
t24 = t18+t20;
t25 = (t17.*t20)./1.0e+3;
t26 = cos(t25);
t27 = sin(t25);
t28 = (t17.*t24)./1.0e+3;
et1 = l1.*t10.*q1.*t12.*qdot0+l1.*t10.*q1.*t12.*qdot1-l2.*t10.*t11.*q2.*qdot0.*2.0-l2.*t10.*t11.*q2.*qdot1.*2.0-l0.*t11.*t12.*qdot0.*t2.*2.0-l1.*t10.*t12.*qdot1.*t4+l0.*t11.*t12.*qdot0.*t13.*2.0-l1.*t10.*t12.*qdot0.*t19-l1.*t10.*t12.*qdot1.*t19+l1.*qdot1.*t10.*t12.*t22-l0.*qdot0.*t11.*t12.*t26.*2.0-l1.*qdot1.*t10.*t12.*t27+t8.*t10.*t11.*q2.*qdot0.*2.0e+3+t8.*t10.*t11.*q2.*qdot1.*2.0e+3-t8.*t10.*t11.*qdot0.*t5.*3.0e+3-t8.*t10.*t11.*qdot1.*t5.*3.0e+3+qdot0.*t8.*t10.*t11.*t22.*3.0e+3+qdot1.*t8.*t10.*t11.*t22.*3.0e+3+l0.*qdot0.*t11.*t12.*cos(t28).*2.0-l1.*l2.*t10.*q2.*qdot1.*t3.*2.0e+3+l1.*l2.*t10.*q2.*qdot1.*t14.*2.0e+3-l0.*l2.*t11.*q2.*qdot0.*t16.*4.0e+3;
et2 = l1.*l2.*q2.*qdot1.*t10.*t23.*2.0e+3+l0.*l2.*q2.*qdot0.*t11.*t27.*4.0e+3-l1.*l2.*q2.*qdot1.*t10.*t26.*2.0e+3+l0.*l2.*t11.*t12.*qdot0.*t2.*2.0e+3+l1.*l2.*t10.*t12.*qdot1.*t4.*1.0e+3-l1.*l2.*t10.*t12.*qdot1.*t5.*1.0e+3-l0.*l2.*t11.*t12.*qdot0.*t13.*2.0e+3+l0.*l2.*t11.*t12.*qdot0.*t14.*2.0e+3+l1.*l2.*t10.*t12.*qdot1.*t16.*1.0e+3-l1.*t10.*q1.*t12.*qdot0.*t2+l0.*q0.*t11.*t12.*qdot0.*t4.*2.0+l1.*q1.*qdot0.*t10.*t12.*t23+l1.*q1.*qdot1.*t10.*t12.*t23-l2.*q2.*qdot0.*t10.*t11.*t23-l2.*q2.*qdot1.*t10.*t11.*t23+l0.*q0.*qdot0.*t11.*t12.*t27.*2.0-l1.*q1.*qdot0.*t10.*t12.*t26+l0.*t9.*t11.*t12.*qdot0.*t2-l1.*t10.*t12.*qdot0.*t3.*t19-l1.*t10.*t12.*qdot1.*t3.*t19+l0.*qdot0.*t9.*t11.*t12.*t26;
et3 = t8.*t10.*t11.*q2.*qdot0.*t3.*1.0e+3+t8.*t10.*t11.*q2.*qdot1.*t3.*1.0e+3-l0.*l2.*q2.*qdot0.*t11.*sin(t28).*4.0e+3-l0.*l2.*t11.*t12.*qdot0.*cos(t15).*2.0e+3+l0.*l2.*t11.*q2.*qdot0.*sin(t15).*4.0e+3+l1.*l2.*t10.*q1.*q2.*qdot0.*t5.*2.0e+3+l1.*l2.*t10.*q1.*q2.*qdot1.*t5.*2.0e+3-l0.*l2.*q0.*t11.*q2.*qdot0.*t14.*4.0e+3-l1.*l2.*t10.*q1.*q2.*qdot0.*t16.*2.0e+3-l1.*l2.*q1.*q2.*qdot0.*t10.*t22.*2.0e+3-l1.*l2.*q1.*q2.*qdot1.*t10.*t22.*2.0e+3+l0.*l2.*q0.*q2.*qdot0.*t11.*t26.*4.0e+3+l1.*l2.*q1.*q2.*qdot0.*t10.*t27.*2.0e+3+l1.*l2.*t10.*q1.*t12.*qdot0.*t2.*1.0e+3-l0.*l2.*q0.*t11.*t12.*qdot0.*t4.*2.0e+3+l0.*l2.*t9.*t11.*q2.*qdot0.*t16.*2.0e+3;
et4 = l1.*l2.*t10.*q1.*t12.*qdot0.*t14.*1.0e+3-l0.*l2.*q0.*t11.*t12.*qdot0.*t16.*2.0e+3-l0.*l2.*q2.*qdot0.*t9.*t11.*t27.*2.0e+3-l0.*l2.*t9.*t11.*t12.*qdot0.*t2.*1.0e+3-l0.*l2.*t9.*t11.*t12.*qdot0.*t14.*1.0e+3;
if ((q1 ~= 0.0) & (q2 ~= 0.0))
    out1 = (l2.*rho2.*1.0./t12.^2.*(et1+et2+et3+et4))./(t10.*t11.*1.0e+3);
else
    out1 = NaN;
end
