function out1 = C32_fun(in1,in2,alpha,in4,in5)
%C32_FUN
%    OUT1 = C32_FUN(IN1,IN2,ALPHA,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Apr-2021 16:22:20

l1 = in4(2,:);
l2 = in4(3,:);
q1 = in1(2,:);
q2 = in1(3,:);
qdot0 = in2(1,:);
qdot1 = in2(2,:);
rho2 = in5(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q1+q2;
t7 = l2.^2;
t8 = q1.^2;
t9 = q1.^3;
t10 = q2.^2;
t13 = 1.0./l2;
t14 = l2.*q1.*1.0e+3;
t11 = cos(t6);
t12 = sin(t6);
t15 = q2+t14;
t16 = (q2.*t13)./1.0e+3;
t17 = sin(t16);
t18 = cos(t16);
t19 = (t13.*t15)./1.0e+3;
t20 = cos(t19);
t21 = sin(t19);
et1 = l1.*t10.*qdot1.*2.0-l1.*l2.*t10.*qdot1.*2.0e+3+l2.*t9.*q2.*qdot0.*2.0+l2.*t9.*q2.*qdot1.*2.0-l1.*t10.*qdot1.*t2.*2.0-l1.*t8.*t10.*qdot0-l1.*t8.*t10.*qdot1+l1.*qdot1.*t10.*t18.*2.0-t7.*t9.*q2.*qdot0.*2.0e+3-t7.*t9.*q2.*qdot1.*2.0e+3+t7.*t9.*qdot0.*t5.*3.0e+3+t7.*t9.*qdot1.*t5.*3.0e+3-qdot0.*t7.*t9.*t17.*3.0e+3-qdot1.*t7.*t9.*t17.*3.0e+3-l1.*qdot1.*t10.*t20.*2.0+l1.*l2.*q2.*qdot1.*t5.*4.0e+3-l1.*l2.*q2.*qdot1.*t12.*4.0e+3-l1.*l2.*q2.*qdot1.*t17.*4.0e+3+l1.*l2.*t10.*qdot1.*t2.*2.0e+3-l1.*l2.*t10.*qdot1.*t3.*2.0e+3+l1.*l2.*t8.*t10.*qdot0.*1.0e+3+l1.*l2.*t8.*t10.*qdot1.*1.0e+3;
et2 = l1.*l2.*t10.*qdot1.*t11.*2.0e+3+l1.*q1.*t10.*qdot0.*t4-l1.*q1.*qdot0.*t10.*t17-l1.*q1.*qdot1.*t10.*t17.*2.0+l2.*q2.*qdot0.*t9.*t18+l2.*q2.*qdot1.*t9.*t18+l1.*t10.*qdot0.*t5.*t14-l1.*qdot0.*t8.*t10.*t18-l1.*qdot1.*t8.*t10.*t18-t7.*t9.*q2.*qdot0.*t3.*1.0e+3-t7.*t9.*q2.*qdot1.*t3.*1.0e+3+l1.*l2.*q2.*qdot1.*t21.*4.0e+3+l1.*q1.*qdot0.*t10.*t21-l1.*l2.*q1.*t10.*qdot0.*t4.*1.0e+3-l1.*l2.*t8.*q2.*qdot0.*t5.*2.0e+3-l1.*l2.*t8.*q2.*qdot1.*t5.*2.0e+3+l1.*l2.*q1.*t10.*qdot1.*t5.*2.0e+3-l1.*l2.*q1.*t10.*qdot0.*t12.*1.0e+3+l1.*l2.*q2.*qdot0.*t8.*t17.*2.0e+3+l1.*l2.*q2.*qdot1.*t8.*t17.*2.0e+3+l1.*l2.*t8.*t10.*qdot0.*t3.*1.0e+3;
et3 = l1.*l2.*t8.*t10.*qdot1.*t3.*1.0e+3+l1.*l2.*q1.*q2.*qdot0.*t20.*2.0e+3+l1.*l2.*q1.*q2.*qdot0.*t3.*2.0e+3+l1.*l2.*q1.*q2.*qdot1.*t3.*4.0e+3-l1.*l2.*q1.*q2.*qdot0.*t11.*2.0e+3-l1.*l2.*q1.*q2.*qdot0.*t18.*2.0e+3-l1.*l2.*q1.*q2.*qdot1.*t18.*4.0e+3;
if ((q1 ~= 0.0) & (q2 ~= 0.0))
    out1 = (l2.*rho2.*1.0./t10.^2.*(et1+et2+et3).*(-1.0./1.0e+3))./t9;
else
    out1 = NaN;
end
