function out1 = C33_fun(in1,in2,alpha,in4,in5)
%C33_FUN
%    OUT1 = C33_FUN(IN1,IN2,ALPHA,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Apr-2021 16:22:20

l2 = in4(3,:);
q2 = in1(3,:);
qdot2 = in2(3,:);
rho2 = in5(3,:);
t2 = sin(q2);
t3 = l2.^2;
t4 = l2.^3;
t5 = q2.^2;
t6 = q2.^3;
t7 = 1.0./l2;
t8 = (q2.*t7)./1.0e+3;
t9 = sin(t8);
if (q2 ~= 0.0)
    out1 = (qdot2.*rho2.*1.0./t5.^3.*(t6+q2.*t3.*1.2e+7-q2.*t4.*1.2e+10+t2.*t4.*3.0e+10-t4.*t6.*1.0e+9-t4.*t9.*3.0e+10-q2.*t4.*cos(q2).*1.8e+10+q2.*t3.*cos(t8).*1.8e+7+l2.*t5.*t9.*3.0e+3-t2.*t4.*t5.*3.0e+9))./3.0e+9;
else
    out1 = NaN;
end
