function G = G_fun(in1,alpha,in3,in4,in5,in6)
%G_FUN
%    G = G_FUN(IN1,ALPHA,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Apr-2021 11:16:22

gx = in6(1,:);
gy = in6(2,:);
k0 = in5(1,:);
k1 = in5(2,:);
k2 = in5(3,:);
l0 = in3(1,:);
l1 = in3(2,:);
l2 = in3(3,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
rho0 = in4(1,:);
rho1 = in4(2,:);
rho2 = in4(3,:);
et1 = (conj(k1).*conj(q1))./conj(l1)+gx.*conj(l2).^2.*1.0./conj(q2).^2.*conj(rho2).*(sin(conj(alpha)+conj(q0)+conj(q1)+conj(q2))-sin(conj(alpha)+conj(q0)+conj(q1)))-(gx.*cos(conj(alpha)+conj(q0)+conj(q1)).*conj(l2).^2.*conj(rho2))./conj(q2)-gy.*cos(conj(alpha)+conj(q0)+conj(q1)).*conj(l1).^2.*1.0./conj(q1).^2.*conj(rho1)+gx.*sin(conj(alpha)+conj(q0)+conj(q1)).*conj(l1).^2.*1.0./conj(q1).^2.*conj(rho1)-(gy.*sin(conj(alpha)+conj(q0)+conj(q1)).*conj(l2).^2.*conj(rho2))./conj(q2)+gx.*conj(l1).^2.*1.0./conj(q1).^3.*conj(rho1).*(cos(conj(alpha)+conj(q0)+conj(q1))-cos(conj(alpha)+conj(q0))).*2.0-gy.*cos(conj(alpha)+conj(q0)).*conj(l1).^2.*1.0./conj(q1).^2.*conj(rho1);
et2 = gy.*conj(l1).^2.*1.0./conj(q1).^3.*conj(rho1).*(sin(conj(alpha)+conj(q0)+conj(q1))-sin(conj(alpha)+conj(q0))).*2.0+gx.*sin(conj(alpha)+conj(q0)).*conj(l1).^2.*1.0./conj(q1).^2.*conj(rho1)-gy.*conj(l2).^2.*1.0./conj(q2).^2.*conj(rho2).*(cos(conj(alpha)+conj(q0)+conj(q1)+conj(q2))-cos(conj(alpha)+conj(q0)+conj(q1)))+(gx.*cos(conj(alpha)+conj(q0)+conj(q1)).*conj(l1).*conj(l2).*conj(rho2))./conj(q1)+(gy.*sin(conj(alpha)+conj(q0)+conj(q1)).*conj(l1).*conj(l2).*conj(rho2))./conj(q1)+gy.*conj(l1).*conj(l2).*1.0./conj(q1).^2.*conj(rho2).*(cos(conj(alpha)+conj(q0)+conj(q1))-cos(conj(alpha)+conj(q0)))-gx.*conj(l1).*conj(l2).*1.0./conj(q1).^2.*conj(rho2).*(sin(conj(alpha)+conj(q0)+conj(q1))-sin(conj(alpha)+conj(q0)));
et3 = (conj(k0).*conj(q0))./conj(l0)+gx.*conj(l2).^2.*1.0./conj(q2).^2.*conj(rho2).*(sin(conj(alpha)+conj(q0)+conj(q1)+conj(q2))-sin(conj(alpha)+conj(q0)+conj(q1)))-gy.*cos(conj(alpha)).*conj(l0).^2.*1.0./conj(q0).^2.*conj(rho0)-(gx.*cos(conj(alpha)+conj(q0)+conj(q1)).*conj(l2).^2.*conj(rho2))./conj(q2)+gx.*sin(conj(alpha)).*conj(l0).^2.*1.0./conj(q0).^2.*conj(rho0)-(gy.*sin(conj(alpha)+conj(q0)+conj(q1)).*conj(l2).^2.*conj(rho2))./conj(q2)-gx.*conj(l0).^2.*1.0./conj(q0).^3.*conj(rho0).*(cos(conj(alpha))-cos(conj(alpha)+conj(q0))).*2.0-gy.*conj(l1).^2.*1.0./conj(q1).^2.*conj(rho1).*(cos(conj(alpha)+conj(q0)+conj(q1))-cos(conj(alpha)+conj(q0)));
et4 = -(gx.*cos(conj(alpha)+conj(q0)).*conj(l1).^2.*conj(rho1))./conj(q1)-gy.*cos(conj(alpha)+conj(q0)).*conj(l0).^2.*1.0./conj(q0).^2.*conj(rho0)-gy.*conj(l0).^2.*1.0./conj(q0).^3.*conj(rho0).*(sin(conj(alpha))-sin(conj(alpha)+conj(q0))).*2.0+gx.*conj(l1).^2.*1.0./conj(q1).^2.*conj(rho1).*(sin(conj(alpha)+conj(q0)+conj(q1))-sin(conj(alpha)+conj(q0)))+gx.*sin(conj(alpha)+conj(q0)).*conj(l0).^2.*1.0./conj(q0).^2.*conj(rho0)-(gy.*sin(conj(alpha)+conj(q0)).*conj(l1).^2.*conj(rho1))./conj(q1)-gy.*conj(l2).^2.*1.0./conj(q2).^2.*conj(rho2).*(cos(conj(alpha)+conj(q0)+conj(q1)+conj(q2))-cos(conj(alpha)+conj(q0)+conj(q1)));
et5 = -gy.*conj(l0).*conj(l1).*1.0./conj(q0).^2.*conj(rho1).*(cos(conj(alpha))-cos(conj(alpha)+conj(q0)))-gy.*conj(l0).*conj(l2).*1.0./conj(q0).^2.*conj(rho2).*(cos(conj(alpha))-cos(conj(alpha)+conj(q0)))+(gx.*conj(l1).*conj(l2).*conj(rho2).*(cos(conj(alpha)+conj(q0)+conj(q1))-cos(conj(alpha)+conj(q0))))./conj(q1)+(gx.*cos(conj(alpha)+conj(q0)).*conj(l0).*conj(l1).*conj(rho1))./conj(q0)+(gx.*cos(conj(alpha)+conj(q0)).*conj(l0).*conj(l2).*conj(rho2))./conj(q0)+gx.*conj(l0).*conj(l1).*1.0./conj(q0).^2.*conj(rho1).*(sin(conj(alpha))-sin(conj(alpha)+conj(q0)))+gx.*conj(l0).*conj(l2).*1.0./conj(q0).^2.*conj(rho2).*(sin(conj(alpha))-sin(conj(alpha)+conj(q0)));
et6 = (gy.*conj(l1).*conj(l2).*conj(rho2).*(sin(conj(alpha)+conj(q0)+conj(q1))-sin(conj(alpha)+conj(q0))))./conj(q1)+(gy.*sin(conj(alpha)+conj(q0)).*conj(l0).*conj(l1).*conj(rho1))./conj(q0)+(gy.*sin(conj(alpha)+conj(q0)).*conj(l0).*conj(l2).*conj(rho2))./conj(q0);
G = [et3+et4+et5+et6;et1+et2;(conj(k2).*conj(q2))./conj(l2)-gy.*cos(conj(alpha)+conj(q0)+conj(q1)+conj(q2)).*conj(l2).^2.*1.0./conj(q2).^2.*conj(rho2)+gy.*conj(l2).^2.*1.0./conj(q2).^3.*conj(rho2).*(sin(conj(alpha)+conj(q0)+conj(q1)+conj(q2))-sin(conj(alpha)+conj(q0)+conj(q1))).*2.0+gx.*sin(conj(alpha)+conj(q0)+conj(q1)+conj(q2)).*conj(l2).^2.*1.0./conj(q2).^2.*conj(rho2)-gy.*cos(conj(alpha)+conj(q0)+conj(q1)).*conj(l2).^2.*1.0./conj(q2).^2.*conj(rho2)+gx.*sin(conj(alpha)+conj(q0)+conj(q1)).*conj(l2).^2.*1.0./conj(q2).^2.*conj(rho2)+gx.*conj(l2).^2.*1.0./conj(q2).^3.*conj(rho2).*(cos(conj(alpha)+conj(q0)+conj(q1)+conj(q2))-cos(conj(alpha)+conj(q0)+conj(q1))).*2.0];
