function theta0 = q2theta0_fun(s,in2)
%Q2THETA0_FUN
%    THETA0 = Q2THETA0_FUN(S,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    08-Apr-2021 21:20:40

q0 = in2(1,:);
theta0 = q0.*s;
