function theta1 = q2theta1_fun(s,in2,alpha,in4)
%Q2THETA1_FUN
%    THETA1 = Q2THETA1_FUN(S,IN2,ALPHA,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    06-Apr-2021 15:14:18

l1 = in4(2,:);
q0 = in2(1,:);
q1 = in2(2,:);
theta1 = alpha+q0+(q1.*s)./l1;
