function theta1 = q2theta1_fun(s,in2)
%Q2THETA1_FUN
%    THETA1 = Q2THETA1_FUN(S,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    08-Apr-2021 21:20:40

q0 = in2(1,:);
q1 = in2(2,:);
theta1 = q0+q1.*s;
