function x0 = q2x0_fun(s,in2)
%Q2X0_FUN
%    X0 = Q2X0_FUN(S,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    08-Apr-2021 21:20:40

q0 = in2(1,:);
x0 = [sin(q0.*s)./q0;-(cos(q0.*s)-1.0)./q0];
