function x0 = q2x0_fun(s,in2,alpha,in4)
%Q2X0_FUN
%    X0 = Q2X0_FUN(S,IN2,ALPHA,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    06-Apr-2021 15:14:18

l0 = in4(1,:);
q0 = in2(1,:);
x0 = [(l0.*(sin(alpha+(q0.*s)./l0)-sin(alpha)))./q0;-(l0.*(cos(alpha+(q0.*s)./l0)-cos(alpha)))./q0];
