function x2 = q2x2_fun(s,in2)
%Q2X2_FUN
%    X2 = Q2X2_FUN(S,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    08-Apr-2021 21:20:40

q0 = in2(1,:);
q1 = in2(2,:);
q2 = in2(3,:);
x2 = [sin(q0)./q0+(sin(q0+q1)-sin(q0))./q1-(sin(q0+q1)-sin(q0+q1+q2.*s))./q2;-(cos(q0)-1.0)./q0-(cos(q0+q1)-cos(q0))./q1+(cos(q0+q1)-cos(q0+q1+q2.*s))./q2];
