function x_m2 = q2xm2_fun(in1,alpha,in3)
%Q2XM2_FUN
%    X_M2 = Q2XM2_FUN(IN1,ALPHA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    29-Mar-2021 16:14:24

l0 = in3(1,:);
l1 = in3(2,:);
l2 = in3(3,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
x_m2 = [(l1.*(sin(alpha+q0+q1)-sin(alpha+q0)))./q1+(l0.*(sin(alpha+q0)-sin(alpha)))./q0-(l2.*(sin(alpha+q0+q1)-sin(alpha+q0+q1+q2)))./q2;-(l0.*(cos(alpha+q0)-cos(alpha)))./q0+(l2.*(cos(alpha+q0+q1)-cos(alpha+q0+q1+q2)))./q2-(l1.*(cos(alpha+q0+q1)-cos(alpha+q0)))./q1];
