function x_m1 = q2xm1_fun(in1,alpha,in3)
%Q2XM1_FUN
%    X_M1 = Q2XM1_FUN(IN1,ALPHA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    29-Mar-2021 15:31:56

l0 = in3(1,:);
l1 = in3(2,:);
q0 = in1(1,:);
q1 = in1(2,:);
x_m1 = [(l1.*(sin(alpha+q0+q1)-sin(alpha+q0)))./q1+(l0.*(sin(alpha+q0)-sin(alpha)))./q0;-(l0.*(cos(alpha+q0)-cos(alpha)))./q0-(l1.*(cos(alpha+q0+q1)-cos(alpha+q0)))./q1];
