function x_m0 = q2xm0_fun(in1,alpha,in3)
%Q2XM0_FUN
%    X_M0 = Q2XM0_FUN(IN1,ALPHA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    29-Mar-2021 15:31:56

l0 = in3(1,:);
q0 = in1(1,:);
x_m0 = [(l0.*(sin(alpha+q0)-sin(alpha)))./q0;-(l0.*(cos(alpha+q0)-cos(alpha)))./q0];
